/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V0_COMMONAPI_DEMO_Demo_App1_SOMEIP_DEPLOYMENT_HPP_
#define V0_COMMONAPI_DEMO_Demo_App1_SOMEIP_DEPLOYMENT_HPP_

#include <v0/commonapi/demo/CommonTypesSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace demo {
namespace DemoApp1_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> stdErrorTypeEnumDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment DemoMethod1_nameDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment DemoMethod1_messageDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment DemoMethodErr1_nameDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment DemoMethodErr1_messageDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment DemoMethodTp1_nameDeployment;

// Broadcast-specific deployments

} // namespace DemoApp1_
} // namespace demo
} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_DEMO_Demo_App1_SOMEIP_DEPLOYMENT_HPP_
