/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_DEMO_Demo_App1_PROXY_HPP_
#define V0_COMMONAPI_DEMO_Demo_App1_PROXY_HPP_

#include <v0/commonapi/demo/DemoApp1ProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace demo {

template <typename ... _AttributeExtensions>
class DemoApp1Proxy
    : virtual public DemoApp1,
      virtual public DemoApp1ProxyBase,
      virtual public _AttributeExtensions... {
public:
    DemoApp1Proxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~DemoApp1Proxy();

    typedef DemoApp1 InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls DemoMethod1 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void DemoMethod1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DemoMethod1 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> DemoMethod1Async(const std::string &_name, DemoMethod1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DemoMethodErr1 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void DemoMethodErr1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, DemoApp1::stdErrorTypeEnum &_error, std::string &_message, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DemoMethodErr1 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> DemoMethodErr1Async(const std::string &_name, DemoMethodErr1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DemoMethodTp1 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void DemoMethodTp1(std::string _name, std::vector< int32_t > _data, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls DemoMethodTp1 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> DemoMethodTp1Async(const std::string &_name, const std::vector< int32_t > &_data, DemoMethodTp1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast DemoStatus1.
     */
    virtual DemoStatus1Event& getDemoStatus1Event() {
        return delegate_->getDemoStatus1Event();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast DemoStatus2.
     */
    virtual DemoStatus2Event& getDemoStatus2Event() {
        return delegate_->getDemoStatus2Event();
    }
    /**
     * Returns the wrapper class that provides access to the attribute uiDemoAttr1.
     */
    virtual UiDemoAttr1Attribute& getUiDemoAttr1Attribute() {
        return delegate_->getUiDemoAttr1Attribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute a1Demo.
     */
    virtual A1DemoAttribute& getA1DemoAttribute() {
        return delegate_->getA1DemoAttribute();
    }



 private:
    std::shared_ptr< DemoApp1ProxyBase> delegate_;
};

typedef DemoApp1Proxy<> DemoApp1ProxyDefault;

namespace DemoApp1Extensions {
    template <template <typename > class _ExtensionType>
    class UiDemoAttr1AttributeExtension {
     public:
        typedef _ExtensionType< DemoApp1ProxyBase::UiDemoAttr1Attribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< DemoApp1ProxyBase::UiDemoAttr1Attribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        UiDemoAttr1AttributeExtension(DemoApp1ProxyBase& proxy): attributeExtension_(proxy.getUiDemoAttr1Attribute()) {
        }
    
        inline extension_type& getUiDemoAttr1AttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class A1DemoAttributeExtension {
     public:
        typedef _ExtensionType< DemoApp1ProxyBase::A1DemoAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< DemoApp1ProxyBase::A1DemoAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        A1DemoAttributeExtension(DemoApp1ProxyBase& proxy): attributeExtension_(proxy.getA1DemoAttribute()) {
        }
    
        inline extension_type& getA1DemoAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace DemoApp1Extensions

//
// DemoApp1Proxy Implementation
//
template <typename ... _AttributeExtensions>
DemoApp1Proxy<_AttributeExtensions...>::DemoApp1Proxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< DemoApp1ProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< DemoApp1ProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
DemoApp1Proxy<_AttributeExtensions...>::~DemoApp1Proxy() {
}

template <typename ... _AttributeExtensions>
void DemoApp1Proxy<_AttributeExtensions...>::DemoMethod1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info) {
    delegate_->DemoMethod1(_name, _internalCallStatus, _message, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> DemoApp1Proxy<_AttributeExtensions...>::DemoMethod1Async(const std::string &_name, DemoMethod1AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->DemoMethod1Async(_name, _callback, _info);
}
template <typename ... _AttributeExtensions>
void DemoApp1Proxy<_AttributeExtensions...>::DemoMethodErr1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, DemoApp1::stdErrorTypeEnum &_error, std::string &_message, const CommonAPI::CallInfo *_info) {
    delegate_->DemoMethodErr1(_name, _internalCallStatus, _error, _message, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> DemoApp1Proxy<_AttributeExtensions...>::DemoMethodErr1Async(const std::string &_name, DemoMethodErr1AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->DemoMethodErr1Async(_name, _callback, _info);
}
template <typename ... _AttributeExtensions>
void DemoApp1Proxy<_AttributeExtensions...>::DemoMethodTp1(std::string _name, std::vector< int32_t > _data, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info) {
    delegate_->DemoMethodTp1(_name, _data, _internalCallStatus, _message, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> DemoApp1Proxy<_AttributeExtensions...>::DemoMethodTp1Async(const std::string &_name, const std::vector< int32_t > &_data, DemoMethodTp1AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->DemoMethodTp1Async(_name, _data, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &DemoApp1Proxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool DemoApp1Proxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool DemoApp1Proxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& DemoApp1Proxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& DemoApp1Proxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> DemoApp1Proxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace demo
} // namespace commonapi
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::commonapi::demo::DemoApp1Proxy,
    _AttributeExtension> {
    typedef typename ::v0::commonapi::demo::DemoApp1Proxy<
            ::v0::commonapi::demo::DemoApp1Extensions::UiDemoAttr1AttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::demo::DemoApp1Extensions::A1DemoAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_DEMO_Demo_App1_PROXY_HPP_
