/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_DEMO_Demo_App1_STUB_HPP_
#define V0_COMMONAPI_DEMO_Demo_App1_STUB_HPP_

#include <functional>
#include <sstream>



#include <v0/commonapi/demo/CommonTypes.hpp>

#include <v0/commonapi/demo/DemoApp1.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace demo {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service DemoApp1. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class DemoApp1StubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual DemoApp1 {
 public:
    /**
    * Sends a broadcast event for DemoStatus1. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireDemoStatus1Event(const int32_t &_uiValue) = 0;
    /**
    * Sends a broadcast event for DemoStatus2. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireDemoStatus2Event() = 0;
    ///Notifies all remote listeners about a change of value of the attribute uiDemoAttr1.
    virtual void fireUiDemoAttr1AttributeChanged(const int32_t &uiDemoAttr1) = 0;
    ///Notifies all remote listeners about a change of value of the attribute a1Demo.
    virtual void fireA1DemoAttributeChanged(const ::v0::commonapi::demo::CommonTypes::a1Struct &a1Demo) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockUiDemoAttr1Attribute(bool _lockAccess) {
        if (_lockAccess) {
            uiDemoAttr1Mutex_.lock();
        } else {
            uiDemoAttr1Mutex_.unlock();
        }
    }
    void lockA1DemoAttribute(bool _lockAccess) {
        if (_lockAccess) {
            a1DemoMutex_.lock();
        } else {
            a1DemoMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex uiDemoAttr1Mutex_;
    std::recursive_mutex a1DemoMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for DemoApp1.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class DemoApp1StubRemoteEvent
{
public:
    virtual ~DemoApp1StubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute uiDemoAttr1
    virtual bool onRemoteSetUiDemoAttr1Attribute(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _value) = 0;
    /// Action callback for remote set requests on the attribute uiDemoAttr1
    virtual void onRemoteUiDemoAttr1AttributeChanged() = 0;
    /// Verification callback for remote set requests on the attribute a1Demo
    virtual bool onRemoteSetA1DemoAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v0::commonapi::demo::CommonTypes::a1Struct _value) = 0;
    /// Action callback for remote set requests on the attribute a1Demo
    virtual void onRemoteA1DemoAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service DemoApp1 to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class DemoApp1Stub
    : public virtual CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>
{
public:
    typedef std::function<void (std::string _message)> DemoMethod1Reply_t;
    typedef std::function<void (DemoApp1::stdErrorTypeEnum _error, std::string _message)> DemoMethodErr1Reply_t;
    typedef std::function<void (std::string _message)> DemoMethodTp1Reply_t;

    virtual ~DemoApp1Stub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 7);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method DemoMethod1.
    virtual void DemoMethod1(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _name, DemoMethod1Reply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method DemoMethodErr1.
    virtual void DemoMethodErr1(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _name, DemoMethodErr1Reply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method DemoMethodTp1.
    virtual void DemoMethodTp1(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _name, std::vector< int32_t > _data, DemoMethodTp1Reply_t _reply) = 0;
    /// Sends a broadcast event for DemoStatus1.
    virtual void fireDemoStatus1Event(const int32_t &_uiValue) {
        auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireDemoStatus1Event(_uiValue);
    }
    /// Sends a broadcast event for DemoStatus2.
    virtual void fireDemoStatus2Event() {
        auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireDemoStatus2Event();
    }
    /// Provides getter access to the attribute uiDemoAttr1
    virtual const int32_t &getUiDemoAttr1Attribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireUiDemoAttr1AttributeChanged(int32_t _value) {
    auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireUiDemoAttr1AttributeChanged(_value);
    }
    void lockUiDemoAttr1Attribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockUiDemoAttr1Attribute(_lockAccess);
    }
    /// Provides getter access to the attribute a1Demo
    virtual const ::v0::commonapi::demo::CommonTypes::a1Struct &getA1DemoAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireA1DemoAttributeChanged(::v0::commonapi::demo::CommonTypes::a1Struct _value) {
    auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireA1DemoAttributeChanged(_value);
    }
    void lockA1DemoAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockA1DemoAttribute(_lockAccess);
    }


    using CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<DemoApp1StubAdapter, DemoApp1StubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef DemoApp1StubRemoteEvent RemoteEventType;
    typedef DemoApp1 StubInterface;
};

} // namespace demo
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_DEMO_Demo_App1_STUB_HPP_
