/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_SOMEIP_PROXY_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_SOMEIP_PROXY_HPP_

#include <v1/someip/testability/ETSProxyBase.hpp>
#include <v1/someip/testability/ETSSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Attribute.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace someip {
namespace testability {

class ETSSomeIPProxy
    : virtual public ETSProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    ETSSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~ETSSomeIPProxy();

    virtual ETSInterfaceVersionAttribute& getETSInterfaceVersionAttribute();

    virtual TestFieldUINT8Attribute& getTestFieldUINT8Attribute();

    virtual TestFieldUINT8ArrayAttribute& getTestFieldUINT8ArrayAttribute();

    virtual TestFieldUINT8ReliableAttribute& getTestFieldUINT8ReliableAttribute();

    virtual TestEventUINT8Event& getTestEventUINT8Event();

    virtual TestEventUINT8ArrayEvent& getTestEventUINT8ArrayEvent();

    virtual TestEventUINT8E2EEvent& getTestEventUINT8E2EEvent();

    virtual TestEventUINT8MulticastEvent& getTestEventUINT8MulticastEvent();

    virtual TestEventUINT8ArrayTPEvent& getTestEventUINT8ArrayTPEvent();

    virtual TestEventUINT32PeriodicEvent& getTestEventUINT32PeriodicEvent();

    virtual TestEventUINT32UpdateOnChangeEvent& getTestEventUINT32UpdateOnChangeEvent();

    virtual TestEventUINT8ReliableEvent& getTestEventUINT8ReliableEvent();

    /*
     * description: 
     * Check byte order handling of parameters.
     */
    virtual void checkByteOrder(uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_checkByteOrder_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> checkByteOrderAsync(const uint8_t &_checkByteOrder_ReqArg1, const uint16_t &_checkByteOrder_ReqArg2, CheckByteOrderAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Activates the remote client prxoy in the server side.
     */
    virtual void clientServiceActivate(uint8_t _clientServiceActivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Deactivates the remote client prxoy in the server side.
     */
    virtual void clientServiceDeactivate(uint8_t _clientServiceDeactivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     */
    virtual void clientServiceGetLastValueOfEventUDPMulticast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPMulticast_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPMulticastAsync(ClientServiceGetLastValueOfEventUDPMulticastAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     */
    virtual void clientServiceGetLastValueOfEventUDPUnicast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPUnicast_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPUnicastAsync(ClientServiceGetLastValueOfEventUDPUnicastAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Subscribe to the event offered by service launched in client side.
     */
    virtual void clientServiceSubscribeEventgroup(uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     */
    virtual void echoBitfields(uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoBitfields_ResArg1, uint16_t &_echoBitfields_ResArg2, uint32_t &_echoBitfields_ResArg3, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoBitfieldsAsync(const uint8_t &_echoBitfields_ReqArg1, const uint16_t &_echoBitfields_ReqArg2, const uint32_t &_echoBitfields_ReqArg3, EchoBitfieldsAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns the input parameters in reverse order.
     */
    virtual void echoCommonDatatypes(bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, CommonAPI::CallStatus &_internalCallStatus, double &_EchoCommonDatatypes_ResArg1, float &_EchoCommonDatatypes_ResArg2, int32_t &_EchoCommonDatatypes_ResArg3, int16_t &_EchoCommonDatatypes_ResArg4, int8_t &_EchoCommonDatatypes_ResArg5, uint32_t &_EchoCommonDatatypes_ResArg6, uint16_t &_EchoCommonDatatypes_ResArg7, uint8_t &_EchoCommonDatatypes_ResArg8, bool &_EchoCommonDatatypes_ResArg9, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoCommonDatatypesAsync(const bool &_EchoCommonDatatypes_ReqArg1, const uint8_t &_EchoCommonDatatypes_ReqArg2, const uint16_t &_EchoCommonDatatypes_ReqArg3, const uint32_t &_EchoCommonDatatypes_ReqArg4, const int8_t &_EchoCommonDatatypes_ReqArg5, const int16_t &_EchoCommonDatatypes_ReqArg6, const int32_t &_EchoCommonDatatypes_ReqArg7, const float &_EchoCommonDatatypes_ReqArg8, const double &_EchoCommonDatatypes_ReqArg9, EchoCommonDatatypesAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the ENUM passed as input parameter.
     */
    virtual void echoENUM(ETS::Enum _echoENUM_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, ETS::Enum &_echoENUM_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoENUMAsync(const ETS::Enum &_echoENUM_ReqArg1, EchoENUMAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the double passed as input parameter.
     */
    virtual void echoFLOAT64(double _echoFLOAT64_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, double &_echoFLOAT64_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoFLOAT64Async(const double &_echoFLOAT64_ReqArg1, EchoFLOAT64AsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the int8 passed as input parameter.
     */
    virtual void echoINT8(int8_t _echoINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, int8_t &_echoINT8_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoINT8Async(const int8_t &_echoINT8_ReqArg1, EchoINT8AsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     */
    virtual void echoStaticUINT8Array(std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_echoStaticUINT8Array_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoStaticUINT8ArrayAsync(const std::vector< uint8_t > &_echoStaticUINT8Array_ReqArg1, EchoStaticUINT8ArrayAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the uint8 passed as input parameter.
     */
    virtual void echoUINT8(uint8_t _echoUINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8Async(const uint8_t &_echoUINT8_ReqArg1, EchoUINT8AsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     */
    virtual void echoUINT8Array(uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array_ResArg1, std::vector< uint8_t > &_echoUINT8Array_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayAsync(const uint32_t &_echoUINT8Array_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array_ReqArg2, EchoUINT8ArrayAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     */
    virtual void echoUINT8Array16BitLength(uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8Array16BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array16BitLength_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8Array16BitLengthAsync(const uint16_t &_echoUINT8Array16BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array16BitLength_ReqArg2, EchoUINT8Array16BitLengthAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     */
    virtual void echoUINT8Array2Dim(uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array2Dim_ResArg1, std::vector< ETS::uint8ArrayReturnArray > &_echoUINT8Array2Dim_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8Array2DimAsync(const uint32_t &_echoUINT8Array2Dim_ReqArg1, const std::vector< ETS::uint8ArrayArray > &_echoUINT8Array2Dim_ReqArg2, EchoUINT8Array2DimAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     */
    virtual void echoUINT8Array8BitLength(uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8Array8BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array8BitLength_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8Array8BitLengthAsync(const uint8_t &_echoUINT8Array8BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array8BitLength_ReqArg2, EchoUINT8Array8BitLengthAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     */
    virtual void echoUINT8ArrayMinSize(uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8ArrayMinSize_ResArg1, std::vector< uint8_t > &_echoUINT8ArrayMinSize_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayMinSizeAsync(const uint32_t &_echoUINT8ArrayMinSize_ReqArg1, const std::vector< uint8_t > &_echoUINT8ArrayMinSize_ReqArg2, EchoUINT8ArrayMinSizeAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     */
    virtual void echoUTF16DYNAMIC(uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF16DYNAMIC_ResArg1, std::string &_echoUTF16DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUTF16DYNAMICAsync(const uint32_t &_echoUTF16DYNAMIC_ReqArg1, const std::string &_echoUTF16DYNAMIC_ReqArg2, EchoUTF16DYNAMICAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     */
    virtual void echoUTF16FIXED(std::string _echoUTF16FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF16FIXED_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUTF16FIXEDAsync(const std::string &_echoUTF16FIXED_ReqArg1, EchoUTF16FIXEDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     */
    virtual void echoUTF8DYNAMIC(uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF8DYNAMIC_ResArg1, std::string &_echoUTF8DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUTF8DYNAMICAsync(const uint32_t &_echoUTF8DYNAMIC_ReqArg1, const std::string &_echoUTF8DYNAMIC_ReqArg2, EchoUTF8DYNAMICAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     */
    virtual void echoUTF8FIXED(std::string _echoUTF8FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF8FIXED_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUTF8FIXEDAsync(const std::string &_echoUTF8FIXED_ReqArg1, EchoUTF8FIXEDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Reset interface to default values.
     */
    virtual void resetInterface(CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     */
    virtual void suspendInterface(uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     */
    virtual void triggerEventUINT8(uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     */
    virtual void triggerEventUINT8Array(uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     */
    virtual void triggerEventUINT8E2E(uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     */
    virtual void triggerEventUINT8Multicast(uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Returns back the e2e data passed as input parameter.
     */
    virtual void echoUINT8E2E(uint16_t _echoUINT8E2E_ReqArg1, uint16_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8E2E_ResArg1, uint16_t &_echoUINT8E2E_ResArg2, uint32_t &_echoUINT8E2E_ResArg3, uint32_t &_echoUINT8E2E_ResArg4, uint8_t &_echoUINT8E2E_ResArg5, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8E2EAsync(const uint16_t &_echoUINT8E2E_ReqArg1, const uint16_t &_echoUINT8E2E_ReqArg2, const uint32_t &_echoUINT8E2E_ReqArg3, const uint32_t &_echoUINT8E2E_ReqArg4, const uint8_t &_echoUINT8E2E_ReqArg5, EchoUINT8E2EAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     */
    virtual void echoUINT8ArrayLengthTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthTPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    virtual void echoUINT8ArrayLengthInTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthInTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthInTPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Sends the uint8 array as reply over SOME/IP TP.
     */
    virtual void echoUINT8ArrayLengthOutTP(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthOutTPAsync(const uint32_t &_inUINT32_ReqArg1, EchoUINT8ArrayLengthOutTPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    virtual void echoUINT8ArrayLengthTPNoResponse(std::vector< uint8_t > _echoUINT8ArrayLengthTPNoResponse_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    virtual void triggerEventUINT8ArrayTP(std::vector< uint8_t > _triggerEventUINT8ArrayTP_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    virtual void triggerEventUINT8ArrayTPNoReqTPPayload(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to triggers an periodic event of type uint32.
     */
    virtual void triggerEventUINT32Periodic(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Requests to triggers an on change event of type uint32.
     */
    virtual void triggerEventUINT32UpdateOnChange(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Activates Test Service in the server side.
     */
    virtual void activateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * Deactivates Test Service in the server side.
     */
    virtual void deactivateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);

    /*
     * description: 
     * The method returns the transfered UINT8 value back to the invoker over reliable endpoint.
     */
    virtual void echoUINT8RELIABLE(uint8_t _echoUINT8RELIABLE_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8RELIABLE_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> echoUINT8RELIABLEAsync(const uint8_t &_echoUINT8RELIABLE_ReqArg1, EchoUINT8RELIABLEAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Get last value of TestEventUINT8Reliable.
     */
    virtual void clientServiceGetLastValueOfEventTCP(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventTCP_ResArg1, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventTCPAsync(ClientServiceGetLastValueOfEventTCPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8 over reliable endpoint.
     */
    virtual void triggerEventUINT8Reliable(uint32_t _triggerEventUINT8Reliable_ReqArg1, uint32_t _triggerEventUINT8Reliable_ReqArg2, uint32_t _triggerEventUINT8Reliable_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::ReadonlyAttribute<ETSInterfaceVersionAttribute, ::v1::someip::testability::ETS_::VersionTypeDeployment_t>> eTSInterfaceVersion_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<TestFieldUINT8Attribute, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>> testFieldUINT8_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<TestFieldUINT8ArrayAttribute, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>> testFieldUINT8Array_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<TestFieldUINT8ReliableAttribute, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>> testFieldUINT8Reliable_;
    CommonAPI::SomeIP::Event<TestEventUINT8Event, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> testEventUINT8_;
    CommonAPI::SomeIP::Event<TestEventUINT8ArrayEvent, CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > >> testEventUINT8Array_;
    CommonAPI::SomeIP::Event<TestEventUINT8E2EEvent, CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t> >, CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t> >, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> testEventUINT8E2E_;
    CommonAPI::SomeIP::Event<TestEventUINT8MulticastEvent, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> testEventUINT8Multicast_;
    CommonAPI::SomeIP::Event<TestEventUINT8ArrayTPEvent, CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > >> testEventUINT8ArrayTP_;
    CommonAPI::SomeIP::Event<TestEventUINT32PeriodicEvent, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >> testEventUINT32Periodic_;
    CommonAPI::SomeIP::Event<TestEventUINT32UpdateOnChangeEvent, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >> testEventUINT32UpdateOnChange_;
    CommonAPI::SomeIP::Event<TestEventUINT8ReliableEvent, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> testEventUINT8Reliable_;

    std::promise<void> completed_;
};

} // namespace testability
} // namespace someip
} // namespace v1

#endif // V1_SOMEIP_TESTABILITY_ETS_SOMEIP_PROXY_HPP_
