/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/someip/testability/ETSSecondaryServiceSomeIPStubAdapter.hpp>
#include <v1/someip/testability/ETSSecondaryService.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createETSSecondaryServiceSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< ETSSecondaryServiceSomeIPStubAdapter<::v1::someip::testability::ETSSecondaryServiceStub>>(_address, _connection, _stub);
}

void initializeETSSecondaryServiceSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:someip.testability.ETSSecondaryService:v1_0:someip.testability.ETSSecondaryService",
         0x102, 0xf4, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "someip.testability.ETSSecondaryService:v1_0",
        &createETSSecondaryServiceSomeIPStubAdapter);
}

INITIALIZER(registerETSSecondaryServiceSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeETSSecondaryServiceSomeIPStubAdapter);
}

} // namespace testability
} // namespace someip
} // namespace v1
