/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_SOMEIP_STUB_ADAPTER_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/someip/testability/ETSStub.hpp>
#include <v1/someip/testability/ETSSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename _Stub = ::v1::someip::testability::ETSStub, typename... _Stubs>
class ETSSomeIPStubAdapterInternal
    : public virtual ETSStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ETSSomeIPStubAdapterHelper;

    ~ETSSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ETSSomeIPStubAdapterHelper::deinit();
    }

    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
     */
    void fireTestEventUINT8Event(const uint8_t &_uINT8Value);

    /*
     * description: 
     * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
     */
    void fireTestEventUINT8ArrayEvent(const std::vector< uint8_t > &_uINT8Array);

    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
     */
    void fireTestEventUINT8E2EEvent(const uint16_t &_length, const uint16_t &_counter, const uint32_t &_dataID, const uint32_t &_CRC, const uint8_t &_uINT8Value);

    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
     */
    void fireTestEventUINT8MulticastEvent(const uint8_t &_uINT8Value);

    /*
     * description: 
     * A broadcast TP event triggered on echoUINT8ArrayLengthTP method request.
     */
    void fireTestEventUINT8ArrayTPEvent(const std::vector< uint8_t > &_outUINT8EventArray);

    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
     */
    void fireTestEventUINT32PeriodicEvent(const uint32_t &_uINT32Value);

    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
     */
    void fireTestEventUINT32UpdateOnChangeEvent(const uint32_t &_uINT32Value);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::someip::testability::ETSStub,
        CommonAPI::Version
    > getETSInterfaceVersionStubDispatcher;

    /*
     * description: 
     * Check byte order handling of parameters.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t, uint16_t>,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > checkByteOrderStubDispatcher;
    
    /*
     * description: 
     * Activates the remote client prxoy in the server side.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > clientServiceActivateStubDispatcher;
    
    /*
     * description: 
     * Deactivates the remote client prxoy in the server side.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > clientServiceDeactivateStubDispatcher;
    
    /*
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< >,
        std::tuple< uint8_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > clientServiceGetLastValueOfEventUDPMulticastStubDispatcher;
    
    /*
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< >,
        std::tuple< uint8_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > clientServiceGetLastValueOfEventUDPUnicastStubDispatcher;
    
    /*
     * description: 
     * Subscribe to the event offered by service launched in client side.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > clientServiceSubscribeEventgroupStubDispatcher;
    
    /*
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t, uint16_t, uint32_t>,
        std::tuple< uint8_t, uint16_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > echoBitfieldsStubDispatcher;
    
    /*
     * description: 
     * Returns the input parameters in reverse order.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< bool, uint8_t, uint16_t, uint32_t, int8_t, int16_t, int32_t, float, double>,
        std::tuple< double, float, int32_t, int16_t, int8_t, uint32_t, uint16_t, uint8_t, bool>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<int8_t>, CommonAPI::SomeIP::IntegerDeployment<int16_t>, CommonAPI::SomeIP::IntegerDeployment<int32_t>, CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment, CommonAPI::SomeIP::IntegerDeployment<int32_t>, CommonAPI::SomeIP::IntegerDeployment<int16_t>, CommonAPI::SomeIP::IntegerDeployment<int8_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::EmptyDeployment>
    > echoCommonDatatypesStubDispatcher;
    
    /*
     * description: 
     * Returns back the ENUM passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< ETS::Enum>,
        std::tuple< ETS::Enum>,
        std::tuple< ::v1::someip::testability::ETS_::EnumDeployment_t>,
        std::tuple< ::v1::someip::testability::ETS_::EnumDeployment_t>
    > echoENUMStubDispatcher;
    
    /*
     * description: 
     * Returns back the double passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< double>,
        std::tuple< double>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    > echoFLOAT64StubDispatcher;
    
    /*
     * description: 
     * Returns back the int8 passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< int8_t>,
        std::tuple< int8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int8_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int8_t>>
    > echoINT8StubDispatcher;
    
    /*
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< std::vector< uint8_t >>,
        std::tuple< std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoStaticUINT8ArrayStubDispatcher;
    
    /*
     * description: 
     * Returns back the uint8 passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t>,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > echoUINT8StubDispatcher;
    
    /*
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, std::vector< uint8_t >>,
        std::tuple< uint32_t, std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoUINT8ArrayStubDispatcher;
    
    /*
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint16_t, std::vector< uint8_t >>,
        std::tuple< uint16_t, std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoUINT8Array16BitLengthStubDispatcher;
    
    /*
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, std::vector< ETS::uint8ArrayArray >>,
        std::tuple< uint32_t, std::vector< ETS::uint8ArrayReturnArray >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayArrayDeployment_t >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment_t >>
    > echoUINT8Array2DimStubDispatcher;
    
    /*
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint8_t, std::vector< uint8_t >>,
        std::tuple< uint8_t, std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoUINT8Array8BitLengthStubDispatcher;
    
    /*
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, std::vector< uint8_t >>,
        std::tuple< uint32_t, std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoUINT8ArrayMinSizeStubDispatcher;
    
    /*
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, std::string>,
        std::tuple< uint32_t, std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::StringDeployment>
    > echoUTF16DYNAMICStubDispatcher;
    
    /*
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > echoUTF16FIXEDStubDispatcher;
    
    /*
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, std::string>,
        std::tuple< uint32_t, std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::StringDeployment>
    > echoUTF8DYNAMICStubDispatcher;
    
    /*
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > echoUTF8FIXEDStubDispatcher;
    
    /*
     * description: 
     * Reset interface to default values.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< >,
        std::tuple< >
    > resetInterfaceStubDispatcher;
    
    /*
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > suspendInterfaceStubDispatcher;
    
    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT8StubDispatcher;
    
    /*
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT8ArrayStubDispatcher;
    
    /*
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT8E2EStubDispatcher;
    
    /*
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t, uint32_t, uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT8MulticastStubDispatcher;
    
    /*
     * description: 
     * Returns back the e2e data passed as input parameter.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint16_t, uint16_t, uint32_t, uint32_t, uint8_t>,
        std::tuple< uint16_t, uint16_t, uint32_t, uint32_t, uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint16_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint32_t>, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > echoUINT8E2EStubDispatcher;
    
    /*
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< std::vector< uint8_t >>,
        std::tuple< std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > echoUINT8ArrayLengthTPStubDispatcher;
    
    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< std::vector< uint8_t >>,
        std::tuple< CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >>
    > triggerEventUINT8ArrayTPStubDispatcher;
    
    /*
     * description: 
     * Requests to triggers an periodic event of type uint32.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT32PeriodicStubDispatcher;
    
    /*
     * description: 
     * Requests to triggers an on change event of type uint32.
     */
    CommonAPI::SomeIP::MethodStubDispatcher<
        ::v1::someip::testability::ETSStub,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > triggerEventUINT32UpdateOnChangeStubDispatcher;
    
    ETSSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ETSSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ETSStub>(_stub)),
        getETSInterfaceVersionStubDispatcher(&ETSStub::lockInterfaceVersionAttribute, &ETSStub::getInterfaceVersion, false, true),
        checkByteOrderStubDispatcher(
            &ETSStub::checkByteOrder,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        clientServiceActivateStubDispatcher(
            &ETSStub::clientServiceActivate,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        clientServiceDeactivateStubDispatcher(
            &ETSStub::clientServiceDeactivate,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        clientServiceGetLastValueOfEventUDPMulticastStubDispatcher(
            &ETSStub::clientServiceGetLastValueOfEventUDPMulticast,
            false,
            _stub->hasElement(3),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        clientServiceGetLastValueOfEventUDPUnicastStubDispatcher(
            &ETSStub::clientServiceGetLastValueOfEventUDPUnicast,
            false,
            _stub->hasElement(4),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        clientServiceSubscribeEventgroupStubDispatcher(
            &ETSStub::clientServiceSubscribeEventgroup,
            false,
            _stub->hasElement(5),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        echoBitfieldsStubDispatcher(
            &ETSStub::echoBitfields,
            false,
            _stub->hasElement(6),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        echoCommonDatatypesStubDispatcher(
            &ETSStub::echoCommonDatatypes,
            false,
            _stub->hasElement(7),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
        ,
        echoENUMStubDispatcher(
            &ETSStub::echoENUM,
            false,
            _stub->hasElement(8),
            std::make_tuple(static_cast< ::v1::someip::testability::ETS_::EnumDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::someip::testability::ETS_::EnumDeployment_t* >(nullptr)))
        
        ,
        echoFLOAT64StubDispatcher(
            &ETSStub::echoFLOAT64,
            false,
            _stub->hasElement(9),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
        ,
        echoINT8StubDispatcher(
            &ETSStub::echoINT8,
            false,
            _stub->hasElement(10),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr)))
        
        ,
        echoStaticUINT8ArrayStubDispatcher(
            &ETSStub::echoStaticUINT8Array,
            false,
            _stub->hasElement(11),
            std::make_tuple(&::v1::someip::testability::ETS_::echoStaticUINT8Array_echoStaticUINT8Array_ReqArg1Deployment),
            std::make_tuple(&::v1::someip::testability::ETS_::echoStaticUINT8Array_echoStaticUINT8Array_ResArg1Deployment))
        
        ,
        echoUINT8StubDispatcher(
            &ETSStub::echoUINT8,
            false,
            _stub->hasElement(12),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        echoUINT8ArrayStubDispatcher(
            &ETSStub::echoUINT8Array,
            false,
            _stub->hasElement(13),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array_echoUINT8Array_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array_echoUINT8Array_ResArg2Deployment))
        
        ,
        echoUINT8Array16BitLengthStubDispatcher(
            &ETSStub::echoUINT8Array16BitLength,
            false,
            _stub->hasElement(14),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array16BitLength_echoUINT8Array16BitLength_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array16BitLength_echoUINT8Array16BitLength_ResArg2Deployment))
        
        ,
        echoUINT8Array2DimStubDispatcher(
            &ETSStub::echoUINT8Array2Dim,
            false,
            _stub->hasElement(15),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array2Dim_echoUINT8Array2Dim_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array2Dim_echoUINT8Array2Dim_ResArg2Deployment))
        
        ,
        echoUINT8Array8BitLengthStubDispatcher(
            &ETSStub::echoUINT8Array8BitLength,
            false,
            _stub->hasElement(16),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array8BitLength_echoUINT8Array8BitLength_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8Array8BitLength_echoUINT8Array8BitLength_ResArg2Deployment))
        
        ,
        echoUINT8ArrayMinSizeStubDispatcher(
            &ETSStub::echoUINT8ArrayMinSize,
            false,
            _stub->hasElement(17),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ResArg2Deployment))
        
        ,
        echoUTF16DYNAMICStubDispatcher(
            &ETSStub::echoUTF16DYNAMIC,
            false,
            _stub->hasElement(18),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUTF16DYNAMIC_echoUTF16DYNAMIC_ReqArg2Deployment),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::someip::testability::ETS_::echoUTF16DYNAMIC_echoUTF16DYNAMIC_ResArg2Deployment))
        
        ,
        echoUTF16FIXEDStubDispatcher(
            &ETSStub::echoUTF16FIXED,
            false,
            _stub->hasElement(19),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUTF16FIXED_echoUTF16FIXED_ReqArg1Deployment),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUTF16FIXED_echoUTF16FIXED_ResArg1Deployment))
        
        ,
        echoUTF8DYNAMICStubDispatcher(
            &ETSStub::echoUTF8DYNAMIC,
            false,
            _stub->hasElement(20),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        echoUTF8FIXEDStubDispatcher(
            &ETSStub::echoUTF8FIXED,
            false,
            _stub->hasElement(21),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUTF8FIXED_echoUTF8FIXED_ReqArg1Deployment),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUTF8FIXED_echoUTF8FIXED_ResArg1Deployment))
        
        ,
        resetInterfaceStubDispatcher(
            &ETSStub::resetInterface,
            false,
            _stub->hasElement(22),
            std::make_tuple())
        
        ,
        suspendInterfaceStubDispatcher(
            &ETSStub::suspendInterface,
            false,
            _stub->hasElement(23),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        triggerEventUINT8StubDispatcher(
            &ETSStub::triggerEventUINT8,
            false,
            _stub->hasElement(24),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        triggerEventUINT8ArrayStubDispatcher(
            &ETSStub::triggerEventUINT8Array,
            false,
            _stub->hasElement(25),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        triggerEventUINT8E2EStubDispatcher(
            &ETSStub::triggerEventUINT8E2E,
            false,
            _stub->hasElement(26),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        triggerEventUINT8MulticastStubDispatcher(
            &ETSStub::triggerEventUINT8Multicast,
            false,
            _stub->hasElement(27),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        echoUINT8E2EStubDispatcher(
            &ETSStub::echoUINT8E2E,
            false,
            _stub->hasElement(31),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        echoUINT8ArrayLengthTPStubDispatcher(
            &ETSStub::echoUINT8ArrayLengthTP,
            false,
            _stub->hasElement(33),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUINT8ArrayLengthTP_inUINT8Array_ReqArg1Deployment),
            std::make_tuple(&::v1::someip::testability::ETS_::echoUINT8ArrayLengthTP_outUINT8Array_ResArg1Deployment))
        
        ,
        triggerEventUINT8ArrayTPStubDispatcher(
            &ETSStub::triggerEventUINT8ArrayTP,
            false,
            _stub->hasElement(34),
            std::make_tuple(&::v1::someip::testability::ETS_::triggerEventUINT8ArrayTP_triggerEventUINT8ArrayTP_ReqArg1Deployment))
        
        ,
        triggerEventUINT32PeriodicStubDispatcher(
            &ETSStub::triggerEventUINT32Periodic,
            false,
            _stub->hasElement(36),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
        ,
        triggerEventUINT32UpdateOnChangeStubDispatcher(
            &ETSStub::triggerEventUINT32UpdateOnChange,
            false,
            _stub->hasElement(38),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
    {
        /*
         * description: 
         * Check byte order handling of parameters.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1f) }, &checkByteOrderStubDispatcher );
        /*
         * description: 
         * Activates the remote client prxoy in the server side.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2f) }, &clientServiceActivateStubDispatcher );
        /*
         * description: 
         * Deactivates the remote client prxoy in the server side.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x30) }, &clientServiceDeactivateStubDispatcher );
        /*
         * description: 
         * Get last value of multicast event triggered by service running in client side.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3d) }, &clientServiceGetLastValueOfEventUDPMulticastStubDispatcher );
        /*
         * description: 
         * Get last value of unicast event triggered by service launched in client side.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3c) }, &clientServiceGetLastValueOfEventUDPUnicastStubDispatcher );
        /*
         * description: 
         * Subscribe to the event offered by service launched in client side.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x32) }, &clientServiceSubscribeEventgroupStubDispatcher );
        /*
         * description: 
         * Reverse the bits of all the input parameters and return it back.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x41) }, &echoBitfieldsStubDispatcher );
        /*
         * description: 
         * Returns the input parameters in reverse order.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x23) }, &echoCommonDatatypesStubDispatcher );
        /*
         * description: 
         * Returns back the ENUM passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x17) }, &echoENUMStubDispatcher );
        /*
         * description: 
         * Returns back the double passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x12) }, &echoFLOAT64StubDispatcher );
        /*
         * description: 
         * Returns back the int8 passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xe) }, &echoINT8StubDispatcher );
        /*
         * description: 
         * Returns back the static array of uint8 passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x36) }, &echoStaticUINT8ArrayStubDispatcher );
        /*
         * description: 
         * Returns back the uint8 passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x8) }, &echoUINT8StubDispatcher );
        /*
         * description: 
         * Returns back the array of uint8 passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x9) }, &echoUINT8ArrayStubDispatcher );
        /*
         * description: 
         * Returns back the input array of uint8 having 16th bit length field.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3f) }, &echoUINT8Array16BitLengthStubDispatcher );
        /*
         * description: 
         * Returns back the 2D-array of uint8 passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x35) }, &echoUINT8Array2DimStubDispatcher );
        /*
         * description: 
         * Returns back the input array of uint8 having 8th bit length field.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3e) }, &echoUINT8Array8BitLengthStubDispatcher );
        /*
         * description: 
         * Returns back the input array of uint8 having at least 3 entries back.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x37) }, &echoUINT8ArrayMinSizeStubDispatcher );
        /*
         * description: 
         * Returns back the UTF16 string of dynamic length passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x16) }, &echoUTF16DYNAMICStubDispatcher );
        /*
         * description: 
         * Returns back the UTF16 string of fixed length passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x14) }, &echoUTF16FIXEDStubDispatcher );
        /*
         * description: 
         * Returns back the UTF8 string of dynamic length passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x15) }, &echoUTF8DYNAMICStubDispatcher );
        /*
         * description: 
         * Returns back the UTF8 string of fixed length passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x13) }, &echoUTF8FIXEDStubDispatcher );
        /*
         * description: 
         * Reset interface to default values.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &resetInterfaceStubDispatcher );
        /*
         * description: 
         * Suspend inteface by stopping offer and resume afterwards.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &suspendInterfaceStubDispatcher );
        /*
         * description: 
         * Requests to trigger an broadcast event of type uint8.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3) }, &triggerEventUINT8StubDispatcher );
        /*
         * description: 
         * Requests to trigger an broadcast event of type array of uint8.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4) }, &triggerEventUINT8ArrayStubDispatcher );
        /*
         * description: 
         * Requests to trigger an broadcast event of e2e data.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x6) }, &triggerEventUINT8E2EStubDispatcher );
        /*
         * description: 
         * Requests to trigger an broadcast event of multicast type.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3a) }, &triggerEventUINT8MulticastStubDispatcher );
        /*
         * description: 
         * Returns back the e2e data passed as input parameter.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xb) }, &echoUINT8E2EStubDispatcher );
        /*
         * description: 
         * Sends the uint8 array over SOME/IP TP.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x70) }, &echoUINT8ArrayLengthTPStubDispatcher );
        /*
         * description: 
         * Requests to triggers an TP Event of type uint8 array.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4d) }, &triggerEventUINT8ArrayTPStubDispatcher );
        /*
         * description: 
         * Requests to triggers an periodic event of type uint32.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4b) }, &triggerEventUINT32PeriodicStubDispatcher );
        /*
         * description: 
         * Requests to triggers an on change event of type uint32.
         */
        ETSSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4c) }, &triggerEventUINT32UpdateOnChangeStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x5));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x5));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8002), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x5));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8004), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x5));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x6));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x800b), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x2));
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x5));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x800c), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x7));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x800d), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x7));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x800e), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

/*
 * description: 
 * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT8Event(const uint8_t &_uINT8Value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8Value(_uINT8Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8001),
            false,
             deployed_uINT8Value 
    );
}

/*
 * description: 
 * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT8ArrayEvent(const std::vector< uint8_t > &_uINT8Array) {
    CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> deployed_uINT8Array(_uINT8Array, &::v1::someip::testability::ETS_::TestEventUINT8Array_uINT8ArrayDeployment);
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8002),
            false,
             deployed_uINT8Array 
    );
}

/*
 * description: 
 * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT8E2EEvent(const uint16_t &_length, const uint16_t &_counter, const uint32_t &_dataID, const uint32_t &_CRC, const uint8_t &_uINT8Value) {
    CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t>> deployed_length(_length, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr));
    CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t>> deployed_counter(_counter, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_dataID(_dataID, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_CRC(_CRC, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8Value(_uINT8Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t> > 
    ,  CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t> > 
    ,  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    ,  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    ,  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8004),
            false,
             deployed_length 
            ,  deployed_counter 
            ,  deployed_dataID 
            ,  deployed_CRC 
            ,  deployed_uINT8Value 
    );
}

/*
 * description: 
 * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT8MulticastEvent(const uint8_t &_uINT8Value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8Value(_uINT8Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x800b),
            false,
             deployed_uINT8Value 
    );
}

/*
 * description: 
 * A broadcast TP event triggered on echoUINT8ArrayLengthTP method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT8ArrayTPEvent(const std::vector< uint8_t > &_outUINT8EventArray) {
    CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> >> deployed_outUINT8EventArray(_outUINT8EventArray, &::v1::someip::testability::ETS_::TestEventUINT8ArrayTP_outUINT8EventArrayDeployment);
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::vector< uint8_t >, CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x800c),
            false,
             deployed_outUINT8EventArray 
    );
}

/*
 * description: 
 * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT32PeriodicEvent(const uint32_t &_uINT32Value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_uINT32Value(_uINT32Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x800d),
            false,
             deployed_uINT32Value 
    );
}

/*
 * description: 
 * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestEventUINT32UpdateOnChangeEvent(const uint32_t &_uINT32Value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_uINT32Value(_uINT32Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x800e),
            false,
             deployed_uINT32Value 
    );
}


template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::someip::testability::ETSStub, typename... _Stubs>
class ETSSomeIPStubAdapter
    : public ETSSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ETSSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ETSSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace testability
} // namespace someip
} // namespace v1

#endif // V1_SOMEIP_TESTABILITY_ETS_SOMEIP_STUB_ADAPTER_HPP_
