/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_SOMEIP_TESTABILITY_ETS_SOMEIP_DEPLOYMENT_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {
namespace ETS_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> EnumDeployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> uint8ArrayArrayDeployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> uint8ArrayReturnArrayDeployment_t;

// Type-specific deployments
COMMONAPI_EXPORT extern ::v1::someip::testability::ETS_::uint8ArrayArrayDeployment_t uint8ArrayArrayDeployment;
COMMONAPI_EXPORT extern ::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment_t uint8ArrayReturnArrayDeployment;

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoStaticUINT8Array_echoStaticUINT8Array_ReqArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoStaticUINT8Array_echoStaticUINT8Array_ResArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array_echoUINT8Array_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array_echoUINT8Array_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array16BitLength_echoUINT8Array16BitLength_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array16BitLength_echoUINT8Array16BitLength_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayArrayDeployment_t > echoUINT8Array2Dim_echoUINT8Array2Dim_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment_t > echoUINT8Array2Dim_echoUINT8Array2Dim_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array8BitLength_echoUINT8Array8BitLength_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array8BitLength_echoUINT8Array8BitLength_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF16DYNAMIC_echoUTF16DYNAMIC_ReqArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF16DYNAMIC_echoUTF16DYNAMIC_ResArg2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF16FIXED_echoUTF16FIXED_ReqArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF16FIXED_echoUTF16FIXED_ResArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF8FIXED_echoUTF8FIXED_ReqArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment echoUTF8FIXED_echoUTF8FIXED_ResArg1Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayLengthTP_inUINT8ArrayDeployment;

// Broadcast-specific deployments
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > TestEventUINT8Array_uINT8ArrayDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > TestEventUINT8TP_outUINT8ArrayDeployment;

} // namespace ETS_
} // namespace testability
} // namespace someip
} // namespace v1

#endif // V1_SOMEIP_TESTABILITY_ETS_SOMEIP_DEPLOYMENT_HPP_
