/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * Testability Service to be activated on client side on clientServiceActivate request.
 */
#include <v1/someip/testability/ETSSecondaryServiceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createETSSecondaryServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ETSSecondaryServiceSomeIPProxy>(_address, _connection);
}

void initializeETSSecondaryServiceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:someip.testability.ETSSecondaryService:v1_0:someip.testability.ETSSecondaryService",
        0x102, 0xf4, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "someip.testability.ETSSecondaryService:v1_0",
        &createETSSecondaryServiceSomeIPProxy);
}

INITIALIZER(registerETSSecondaryServiceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeETSSecondaryServiceSomeIPProxy);
}

ETSSecondaryServiceSomeIPProxy::ETSSecondaryServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          secondaryEventUINT8_(*this, 0x8, CommonAPI::SomeIP::event_id_t(0x8085), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr))),
          secondaryMulticastEventUINT8_(*this, 0x9, CommonAPI::SomeIP::event_id_t(0x8086), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr))),
          secondaryEventUINT8Reliable_(*this, 0xa, CommonAPI::SomeIP::event_id_t(0x8087), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
{
}

ETSSecondaryServiceSomeIPProxy::~ETSSecondaryServiceSomeIPProxy() {
    completed_.set_value();
}


ETSSecondaryServiceSomeIPProxy::SecondaryEventUINT8Event& ETSSecondaryServiceSomeIPProxy::getSecondaryEventUINT8Event() {
    return secondaryEventUINT8_;
}
ETSSecondaryServiceSomeIPProxy::SecondaryMulticastEventUINT8Event& ETSSecondaryServiceSomeIPProxy::getSecondaryMulticastEventUINT8Event() {
    return secondaryMulticastEventUINT8_;
}
ETSSecondaryServiceSomeIPProxy::SecondaryEventUINT8ReliableEvent& ETSSecondaryServiceSomeIPProxy::getSecondaryEventUINT8ReliableEvent() {
    return secondaryEventUINT8Reliable_;
}

void ETSSecondaryServiceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> ETSSecondaryServiceSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace testability
} // namespace someip
} // namespace v1
