/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/someip/testability/ETSSomeIPDeployment.hpp>

namespace v1 {
namespace someip {
namespace testability {
namespace ETS_ {

// Type-specific deployments
::v1::someip::testability::ETS_::uint8ArrayArrayDeployment_t uint8ArrayArrayDeployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 4);
::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment_t uint8ArrayReturnArrayDeployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 4);

// Attribute-specific deployments

// Argument-specific deployment
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoStaticUINT8Array_echoStaticUINT8Array_ReqArg1Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 5, 5, 0);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoStaticUINT8Array_echoStaticUINT8Array_ResArg1Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 5, 5, 0);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array_echoUINT8Array_ReqArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array_echoUINT8Array_ResArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array16BitLength_echoUINT8Array16BitLength_ReqArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 2);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array16BitLength_echoUINT8Array16BitLength_ResArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 2);
CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayArrayDeployment_t > echoUINT8Array2Dim_echoUINT8Array2Dim_ReqArg2Deployment(&::v1::someip::testability::ETS_::uint8ArrayArrayDeployment, 0, 5, 4);
CommonAPI::SomeIP::ArrayDeployment< ::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment_t > echoUINT8Array2Dim_echoUINT8Array2Dim_ResArg2Deployment(&::v1::someip::testability::ETS_::uint8ArrayReturnArrayDeployment, 0, 5, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array8BitLength_echoUINT8Array8BitLength_ReqArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 1);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8Array8BitLength_echoUINT8Array8BitLength_ResArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 5, 1);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ReqArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 3, 5, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayMinSize_echoUINT8ArrayMinSize_ResArg2Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 3, 5, 4);
CommonAPI::SomeIP::StringDeployment echoUTF16DYNAMIC_echoUTF16DYNAMIC_ReqArg2Deployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16BE);
CommonAPI::SomeIP::StringDeployment echoUTF16DYNAMIC_echoUTF16DYNAMIC_ResArg2Deployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16BE);
CommonAPI::SomeIP::StringDeployment echoUTF16FIXED_echoUTF16FIXED_ReqArg1Deployment(64, 0, CommonAPI::SomeIP::StringEncoding::UTF16BE);
CommonAPI::SomeIP::StringDeployment echoUTF16FIXED_echoUTF16FIXED_ResArg1Deployment(64, 0, CommonAPI::SomeIP::StringEncoding::UTF16BE);
CommonAPI::SomeIP::StringDeployment echoUTF8FIXED_echoUTF8FIXED_ReqArg1Deployment(64, 0, CommonAPI::SomeIP::StringEncoding::UTF8);
CommonAPI::SomeIP::StringDeployment echoUTF8FIXED_echoUTF8FIXED_ResArg1Deployment(64, 0, CommonAPI::SomeIP::StringEncoding::UTF8);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayLengthTP_inUINT8Array_ReqArg1Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 50005, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > echoUINT8ArrayLengthTP_outUINT8Array_ResArg1Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 50005, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > triggerEventUINT8ArrayTP_triggerEventUINT8ArrayTP_ReqArg1Deployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 50005, 4);

// Broadcast-specific deployments
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > TestEventUINT8Array_uINT8ArrayDeployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 2000, 4);
CommonAPI::SomeIP::ArrayDeployment< CommonAPI::SomeIP::IntegerDeployment<uint8_t> > TestEventUINT8ArrayTP_outUINT8EventArrayDeployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 50005, 4);

} // namespace ETS_
} // namespace testability
} // namespace someip
} // namespace v1
