/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * Testability Service to be activated on client side on clientServiceActivate request.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_SECONDARY_SERVICE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_SECONDARY_SERVICE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/someip/testability/ETSSecondaryServiceStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename _Stub = ::v1::someip::testability::ETSSecondaryServiceStub, typename... _Stubs>
class ETSSecondaryServiceSomeIPStubAdapterInternal
    : public virtual ETSSecondaryServiceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ETSSecondaryServiceSomeIPStubAdapterHelper;

    ~ETSSecondaryServiceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ETSSecondaryServiceSomeIPStubAdapterHelper::deinit();
    }

    /*
     * description: 
     * A broadcast event to support clientServiceSubscribeEventgroup request.
     */
    void fireSecondaryEventUINT8Event(const uint8_t &_uINT8Value);

    /*
     * description: 
     * A broadcast event of type multicast to support clientServiceSubscribeEventgroup request.
     */
    void fireSecondaryMulticastEventUINT8Event(const uint8_t &_uINT8Value);

    /*
     * description: 
     * A Reliable type broadcast event to support clientServiceSubscribeEventgroup request.
     */
    void fireSecondaryEventUINT8ReliableEvent(const uint8_t &_uINT8ValueReliable);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::someip::testability::ETSSecondaryServiceStub,
        CommonAPI::Version
    > getETSSecondaryServiceInterfaceVersionStubDispatcher;

    ETSSecondaryServiceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ETSSecondaryServiceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ETSSecondaryServiceStub>(_stub)),
        getETSSecondaryServiceInterfaceVersionStubDispatcher(&ETSSecondaryServiceStub::lockInterfaceVersionAttribute, &ETSSecondaryServiceStub::getInterfaceVersion, false, true)
    {
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x8));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8085), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x9));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8086), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0xa));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8087), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

/*
 * description: 
 * A broadcast event to support clientServiceSubscribeEventgroup request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSecondaryEventUINT8Event(const uint8_t &_uINT8Value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8Value(_uINT8Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8085),
            false,
             deployed_uINT8Value 
    );
}

/*
 * description: 
 * A broadcast event of type multicast to support clientServiceSubscribeEventgroup request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSecondaryMulticastEventUINT8Event(const uint8_t &_uINT8Value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8Value(_uINT8Value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8086),
            false,
             deployed_uINT8Value 
    );
}

/*
 * description: 
 * A Reliable type broadcast event to support clientServiceSubscribeEventgroup request.
 */
template <typename _Stub, typename... _Stubs>
void ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSecondaryEventUINT8ReliableEvent(const uint8_t &_uINT8ValueReliable) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployed_uINT8ValueReliable(_uINT8ValueReliable, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8087),
            false,
             deployed_uINT8ValueReliable 
    );
}


template <typename _Stub, typename... _Stubs>
void ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::someip::testability::ETSSecondaryServiceStub, typename... _Stubs>
class ETSSecondaryServiceSomeIPStubAdapter
    : public ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ETSSecondaryServiceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ETSSecondaryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace testability
} // namespace someip
} // namespace v1

#endif // V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_SOMEIP_STUB_ADAPTER_HPP_
