/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * Second Test Service for service port validation.
 */
#include <v1/someip/testability/ETSTestService2SomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createETSTestService2SomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ETSTestService2SomeIPProxy>(_address, _connection);
}

void initializeETSTestService2SomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:someip.testability.ETSTestService2:v1_0:someip.testability.ETSTestService2Context1",
        0x104, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "someip.testability.ETSTestService2:v1_0",
        &createETSTestService2SomeIPProxy);
}

INITIALIZER(registerETSTestService2SomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeETSTestService2SomeIPProxy);
}

ETSTestService2SomeIPProxy::ETSTestService2SomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

ETSTestService2SomeIPProxy::~ETSTestService2SomeIPProxy() {
    completed_.set_value();
}



/*
 * description: 
 * Sends the uint32 value as reply.
 */
void ETSTestService2SomeIPProxy::echoUINT32(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_inUINT32_ReqArg1(_inUINT32_ReqArg1, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_outUINT32_ResArg1(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x51),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_inUINT32_ReqArg1,
        _internalCallStatus,
        deploy_outUINT32_ResArg1);
    _outUINT32_ResArg1 = deploy_outUINT32_ResArg1.getValue();
}

std::future<CommonAPI::CallStatus> ETSTestService2SomeIPProxy::echoUINT32Async(const uint32_t &_inUINT32_ReqArg1, EchoUINT32AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_inUINT32_ReqArg1(_inUINT32_ReqArg1, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_outUINT32_ResArg1(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x51),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_inUINT32_ReqArg1,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > _outUINT32_ResArg1) {
            if (_callback)
                _callback(_internalCallStatus, _outUINT32_ResArg1.getValue());
        },
        std::make_tuple(deploy_outUINT32_ResArg1));
}

void ETSTestService2SomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> ETSTestService2SomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace testability
} // namespace someip
} // namespace v1
