/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * First Test Service for service port validation.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_TEST_SERVICE1_SOMEIP_STUB_ADAPTER_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_TEST_SERVICE1_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/someip/testability/ETSTestService1Stub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename _Stub = ::v1::someip::testability::ETSTestService1Stub, typename... _Stubs>
class ETSTestService1SomeIPStubAdapterInternal
    : public virtual ETSTestService1StubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ETSTestService1SomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ETSTestService1SomeIPStubAdapterHelper;

    ~ETSTestService1SomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ETSTestService1SomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::someip::testability::ETSTestService1Stub,
        CommonAPI::Version
    > getETSTestService1InterfaceVersionStubDispatcher;

    /*
     * description: 
     * Sends the uint32 value as reply.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::someip::testability::ETSTestService1Stub,
        std::tuple< uint32_t>,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>
    > echoUINT32StubDispatcher;
    
    ETSTestService1SomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ETSTestService1SomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ETSTestService1Stub>(_stub)),
        getETSTestService1InterfaceVersionStubDispatcher(&ETSTestService1Stub::lockInterfaceVersionAttribute, &ETSTestService1Stub::getInterfaceVersion, false, true),
        echoUINT32StubDispatcher(
            &ETSTestService1Stub::echoUINT32,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
        
    {
        /*
         * description: 
         * Sends the uint32 value as reply.
         */
        ETSTestService1SomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x50) }, &echoUINT32StubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void ETSTestService1SomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void ETSTestService1SomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::someip::testability::ETSTestService1Stub, typename... _Stubs>
class ETSTestService1SomeIPStubAdapter
    : public ETSTestService1SomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ETSTestService1SomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ETSTestService1SomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace testability
} // namespace someip
} // namespace v1

#endif // V1_SOMEIP_TESTABILITY_ETS_Test_Service1_SOMEIP_STUB_ADAPTER_HPP_
