/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_SOMEIP_TESTABILITY_ETS_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <vector>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

class ETS {
public:
    virtual ~ETS() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct Enum : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            UNKNOWN = 1,
            ONE = 2,
            TWO = 3,
            THREE = 4,
            FOUR = 5
        };
    
        Enum()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::UNKNOWN)) {}
        Enum(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::UNKNOWN):
                case static_cast< uint8_t>(Literal::ONE):
                case static_cast< uint8_t>(Literal::TWO):
                case static_cast< uint8_t>(Literal::THREE):
                case static_cast< uint8_t>(Literal::FOUR):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const Enum &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const Enum &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const Enum &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const Enum &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const Enum &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const Enum &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::UNKNOWN): return "UNKNOWN";
            case static_cast< uint8_t>(Literal::ONE): return "ONE";
            case static_cast< uint8_t>(Literal::TWO): return "TWO";
            case static_cast< uint8_t>(Literal::THREE): return "THREE";
            case static_cast< uint8_t>(Literal::FOUR): return "FOUR";
            default: return "UNDEFINED";
            }
        }
    };
    struct VersionType : CommonAPI::Struct< uint8_t, uint32_t> {
    
        VersionType()
        {
            std::get< 0>(values_) = 0u;
            std::get< 1>(values_) = 0ul;
        }
        VersionType(const uint8_t &_majorVersion, const uint32_t &_minorVersion)
        {
            std::get< 0>(values_) = _majorVersion;
            std::get< 1>(values_) = _minorVersion;
        }
        inline const uint8_t &getMajorVersion() const { return std::get< 0>(values_); }
        inline void setMajorVersion(const uint8_t &_value) { std::get< 0>(values_) = _value; }
        inline const uint32_t &getMinorVersion() const { return std::get< 1>(values_); }
        inline void setMinorVersion(const uint32_t &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const VersionType& _other) const {
        return (getMajorVersion() == _other.getMajorVersion() && getMinorVersion() == _other.getMinorVersion());
        }
        inline bool operator!=(const VersionType &_other) const {
            return !((*this) == _other);
        }
    
    };
    typedef std::vector< uint8_t> uint8ArrayArray;
    typedef std::vector< uint8_t> uint8ArrayReturnArray;
};

const char* ETS::getInterface() {
    return ("someip.testability.ETS:v1_0");
}

CommonAPI::Version ETS::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace testability
} // namespace someip
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_HPP_
