/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_SOMEIP_TESTABILITY_ETS_PROXY_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_PROXY_HPP_

#include <v1/someip/testability/ETSProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename ... _AttributeExtensions>
class ETSProxy
    : virtual public ETS,
      virtual public ETSProxyBase,
      virtual public _AttributeExtensions... {
public:
    ETSProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ETSProxy();

    typedef ETS InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * Check byte order handling of parameters.
     * Calls checkByteOrder with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void checkByteOrder(uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_checkByteOrder_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls checkByteOrder with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> checkByteOrderAsync(const uint8_t &_checkByteOrder_ReqArg1, const uint16_t &_checkByteOrder_ReqArg2, CheckByteOrderAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Activates the remote client prxoy in the server side.
     * Calls clientServiceActivate with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceActivate(uint8_t _clientServiceActivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Deactivates the remote client prxoy in the server side.
     * Calls clientServiceDeactivate with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceDeactivate(uint8_t _clientServiceDeactivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     * Calls clientServiceGetLastValueOfEventUDPMulticast with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceGetLastValueOfEventUDPMulticast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPMulticast_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls clientServiceGetLastValueOfEventUDPMulticast with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPMulticastAsync(ClientServiceGetLastValueOfEventUDPMulticastAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     * Calls clientServiceGetLastValueOfEventUDPUnicast with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceGetLastValueOfEventUDPUnicast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPUnicast_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls clientServiceGetLastValueOfEventUDPUnicast with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPUnicastAsync(ClientServiceGetLastValueOfEventUDPUnicastAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Subscribe to the event offered by service launched in client side.
     * Calls clientServiceSubscribeEventgroup with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceSubscribeEventgroup(uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     * Calls echoBitfields with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoBitfields(uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoBitfields_ResArg1, uint16_t &_echoBitfields_ResArg2, uint32_t &_echoBitfields_ResArg3, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoBitfields with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoBitfieldsAsync(const uint8_t &_echoBitfields_ReqArg1, const uint16_t &_echoBitfields_ReqArg2, const uint32_t &_echoBitfields_ReqArg3, EchoBitfieldsAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns the input parameters in reverse order.
     * Calls echoCommonDatatypes with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoCommonDatatypes(bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, CommonAPI::CallStatus &_internalCallStatus, double &_EchoCommonDatatypes_ResArg1, float &_EchoCommonDatatypes_ResArg2, int32_t &_EchoCommonDatatypes_ResArg3, int16_t &_EchoCommonDatatypes_ResArg4, int8_t &_EchoCommonDatatypes_ResArg5, uint32_t &_EchoCommonDatatypes_ResArg6, uint16_t &_EchoCommonDatatypes_ResArg7, uint8_t &_EchoCommonDatatypes_ResArg8, bool &_EchoCommonDatatypes_ResArg9, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoCommonDatatypes with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoCommonDatatypesAsync(const bool &_EchoCommonDatatypes_ReqArg1, const uint8_t &_EchoCommonDatatypes_ReqArg2, const uint16_t &_EchoCommonDatatypes_ReqArg3, const uint32_t &_EchoCommonDatatypes_ReqArg4, const int8_t &_EchoCommonDatatypes_ReqArg5, const int16_t &_EchoCommonDatatypes_ReqArg6, const int32_t &_EchoCommonDatatypes_ReqArg7, const float &_EchoCommonDatatypes_ReqArg8, const double &_EchoCommonDatatypes_ReqArg9, EchoCommonDatatypesAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the ENUM passed as input parameter.
     * Calls echoENUM with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoENUM(ETS::Enum _echoENUM_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, ETS::Enum &_echoENUM_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoENUM with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoENUMAsync(const ETS::Enum &_echoENUM_ReqArg1, EchoENUMAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the double passed as input parameter.
     * Calls echoFLOAT64 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoFLOAT64(double _echoFLOAT64_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, double &_echoFLOAT64_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoFLOAT64 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoFLOAT64Async(const double &_echoFLOAT64_ReqArg1, EchoFLOAT64AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the int8 passed as input parameter.
     * Calls echoINT8 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoINT8(int8_t _echoINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, int8_t &_echoINT8_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoINT8 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoINT8Async(const int8_t &_echoINT8_ReqArg1, EchoINT8AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     * Calls echoStaticUINT8Array with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoStaticUINT8Array(std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_echoStaticUINT8Array_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoStaticUINT8Array with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoStaticUINT8ArrayAsync(const std::vector< uint8_t > &_echoStaticUINT8Array_ReqArg1, EchoStaticUINT8ArrayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the uint8 passed as input parameter.
     * Calls echoUINT8 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8(uint8_t _echoUINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8Async(const uint8_t &_echoUINT8_ReqArg1, EchoUINT8AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     * Calls echoUINT8Array with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8Array(uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array_ResArg1, std::vector< uint8_t > &_echoUINT8Array_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8Array with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayAsync(const uint32_t &_echoUINT8Array_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array_ReqArg2, EchoUINT8ArrayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     * Calls echoUINT8Array16BitLength with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8Array16BitLength(uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8Array16BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array16BitLength_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8Array16BitLength with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array16BitLengthAsync(const uint16_t &_echoUINT8Array16BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array16BitLength_ReqArg2, EchoUINT8Array16BitLengthAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     * Calls echoUINT8Array2Dim with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8Array2Dim(uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array2Dim_ResArg1, std::vector< ETS::uint8ArrayReturnArray > &_echoUINT8Array2Dim_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8Array2Dim with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array2DimAsync(const uint32_t &_echoUINT8Array2Dim_ReqArg1, const std::vector< ETS::uint8ArrayArray > &_echoUINT8Array2Dim_ReqArg2, EchoUINT8Array2DimAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     * Calls echoUINT8Array8BitLength with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8Array8BitLength(uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8Array8BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array8BitLength_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8Array8BitLength with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array8BitLengthAsync(const uint8_t &_echoUINT8Array8BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array8BitLength_ReqArg2, EchoUINT8Array8BitLengthAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     * Calls echoUINT8ArrayMinSize with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8ArrayMinSize(uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8ArrayMinSize_ResArg1, std::vector< uint8_t > &_echoUINT8ArrayMinSize_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8ArrayMinSize with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayMinSizeAsync(const uint32_t &_echoUINT8ArrayMinSize_ReqArg1, const std::vector< uint8_t > &_echoUINT8ArrayMinSize_ReqArg2, EchoUINT8ArrayMinSizeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     * Calls echoUTF16DYNAMIC with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUTF16DYNAMIC(uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF16DYNAMIC_ResArg1, std::string &_echoUTF16DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUTF16DYNAMIC with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUTF16DYNAMICAsync(const uint32_t &_echoUTF16DYNAMIC_ReqArg1, const std::string &_echoUTF16DYNAMIC_ReqArg2, EchoUTF16DYNAMICAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     * Calls echoUTF16FIXED with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUTF16FIXED(std::string _echoUTF16FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF16FIXED_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUTF16FIXED with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUTF16FIXEDAsync(const std::string &_echoUTF16FIXED_ReqArg1, EchoUTF16FIXEDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     * Calls echoUTF8DYNAMIC with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUTF8DYNAMIC(uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF8DYNAMIC_ResArg1, std::string &_echoUTF8DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUTF8DYNAMIC with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUTF8DYNAMICAsync(const uint32_t &_echoUTF8DYNAMIC_ReqArg1, const std::string &_echoUTF8DYNAMIC_ReqArg2, EchoUTF8DYNAMICAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     * Calls echoUTF8FIXED with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUTF8FIXED(std::string _echoUTF8FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF8FIXED_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUTF8FIXED with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUTF8FIXEDAsync(const std::string &_echoUTF8FIXED_ReqArg1, EchoUTF8FIXEDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Reset interface to default values.
     * Calls resetInterface with Fire&Forget semantics.
     *
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void resetInterface(CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     * Calls suspendInterface with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void suspendInterface(uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     * Calls triggerEventUINT8 with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8(uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     * Calls triggerEventUINT8Array with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8Array(uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     * Calls triggerEventUINT8E2E with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8E2E(uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     * Calls triggerEventUINT8Multicast with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8Multicast(uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8.
     */
    virtual TestEventUINT8Event& getTestEventUINT8Event() {
        return delegate_->getTestEventUINT8Event();
    }
    /*
     * description: 
     * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8Array.
     */
    virtual TestEventUINT8ArrayEvent& getTestEventUINT8ArrayEvent() {
        return delegate_->getTestEventUINT8ArrayEvent();
    }
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8E2E.
     */
    virtual TestEventUINT8E2EEvent& getTestEventUINT8E2EEvent() {
        return delegate_->getTestEventUINT8E2EEvent();
    }
    /**
     * description: 
     * Returns back the e2e data passed as input parameter.
     * Calls echoUINT8E2E with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8E2E(uint16_t _echoUINT8E2E_ReqArg1, uint16_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8E2E_ResArg1, uint16_t &_echoUINT8E2E_ResArg2, uint32_t &_echoUINT8E2E_ResArg3, uint32_t &_echoUINT8E2E_ResArg4, uint8_t &_echoUINT8E2E_ResArg5, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8E2E with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8E2EAsync(const uint16_t &_echoUINT8E2E_ReqArg1, const uint16_t &_echoUINT8E2E_ReqArg2, const uint32_t &_echoUINT8E2E_ReqArg3, const uint32_t &_echoUINT8E2E_ReqArg4, const uint8_t &_echoUINT8E2E_ReqArg5, EchoUINT8E2EAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8Multicast.
     */
    virtual TestEventUINT8MulticastEvent& getTestEventUINT8MulticastEvent() {
        return delegate_->getTestEventUINT8MulticastEvent();
    }
    /**
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     * Calls echoUINT8ArrayLengthTP with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8ArrayLengthTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8ArrayLengthTP with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthTPAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     * Calls echoUINT8ArrayLengthInTP with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8ArrayLengthInTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8ArrayLengthInTP with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthInTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthInTPAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Sends the uint8 array as reply over SOME/IP TP.
     * Calls echoUINT8ArrayLengthOutTP with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8ArrayLengthOutTP(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8ArrayLengthOutTP with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayLengthOutTPAsync(const uint32_t &_inUINT32_ReqArg1, EchoUINT8ArrayLengthOutTPAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     * Calls echoUINT8ArrayLengthTPNoResponse with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8ArrayLengthTPNoResponse(std::vector< uint8_t > _echoUINT8ArrayLengthTPNoResponse_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     * Calls triggerEventUINT8ArrayTP with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8ArrayTP(std::vector< uint8_t > _triggerEventUINT8ArrayTP_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * A broadcast TP event triggered on triggerEventUINT8ArrayTP method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8ArrayTP.
     */
    virtual TestEventUINT8ArrayTPEvent& getTestEventUINT8ArrayTPEvent() {
        return delegate_->getTestEventUINT8ArrayTPEvent();
    }
    /**
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     * Calls triggerEventUINT8ArrayTPNoReqTPPayload with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8ArrayTPNoReqTPPayload(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Requests to triggers an periodic event of type uint32.
     * Calls triggerEventUINT32Periodic with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT32Periodic(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT32Periodic.
     */
    virtual TestEventUINT32PeriodicEvent& getTestEventUINT32PeriodicEvent() {
        return delegate_->getTestEventUINT32PeriodicEvent();
    }
    /**
     * description: 
     * Requests to triggers an on change event of type uint32.
     * Calls triggerEventUINT32UpdateOnChange with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT32UpdateOnChange(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT32UpdateOnChange.
     */
    virtual TestEventUINT32UpdateOnChangeEvent& getTestEventUINT32UpdateOnChangeEvent() {
        return delegate_->getTestEventUINT32UpdateOnChangeEvent();
    }
    /**
     * description: 
     * Activates Test Service in the server side.
     * Calls activateTestSerivce with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void activateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);
    /**
     * description: 
     * Deactivates Test Service in the server side.
     * Calls deactivateTestSerivce with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void deactivateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus);
    /*
     * description: 
     * A field for notifying version information.
     */
    /**
     * Returns the wrapper class that provides access to the attribute ETSInterfaceVersion.
     */
    virtual ETSInterfaceVersionAttribute& getETSInterfaceVersionAttribute() {
        return delegate_->getETSInterfaceVersionAttribute();
    }
    /*
     * description: 
     * A field of UINT8 type.
     */
    /**
     * Returns the wrapper class that provides access to the attribute TestFieldUINT8.
     */
    virtual TestFieldUINT8Attribute& getTestFieldUINT8Attribute() {
        return delegate_->getTestFieldUINT8Attribute();
    }
    /*
     * description: 
     * A field of UINT8 array.
     */
    /**
     * Returns the wrapper class that provides access to the attribute TestFieldUINT8Array.
     */
    virtual TestFieldUINT8ArrayAttribute& getTestFieldUINT8ArrayAttribute() {
        return delegate_->getTestFieldUINT8ArrayAttribute();
    }
    /*
     * description: 
     * A field of UINT8 type over reliable endpoint.
     */
    /**
     * Returns the wrapper class that provides access to the attribute TestFieldUINT8Reliable.
     */
    virtual TestFieldUINT8ReliableAttribute& getTestFieldUINT8ReliableAttribute() {
        return delegate_->getTestFieldUINT8ReliableAttribute();
    }
    /**
     * description: 
     * The method returns the transfered UINT8 value back to the invoker over reliable endpoint.
     * Calls echoUINT8RELIABLE with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT8RELIABLE(uint8_t _echoUINT8RELIABLE_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8RELIABLE_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT8RELIABLE with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT8RELIABLEAsync(const uint8_t &_echoUINT8RELIABLE_ReqArg1, EchoUINT8RELIABLEAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8Reliable method request over tcp endpoint.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast TestEventUINT8Reliable.
     */
    virtual TestEventUINT8ReliableEvent& getTestEventUINT8ReliableEvent() {
        return delegate_->getTestEventUINT8ReliableEvent();
    }
    /**
     * description: 
     * Get last value of TestEventUINT8Reliable.
     * Calls clientServiceGetLastValueOfEventTCP with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clientServiceGetLastValueOfEventTCP(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventTCP_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls clientServiceGetLastValueOfEventTCP with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventTCPAsync(ClientServiceGetLastValueOfEventTCPAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Requests to trigger an broadcast event of type uint8 over reliable endpoint.
     * Calls triggerEventUINT8Reliable with Fire&Forget semantics.
     *
     * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void triggerEventUINT8Reliable(uint32_t _triggerEventUINT8Reliable_ReqArg1, uint32_t _triggerEventUINT8Reliable_ReqArg2, uint32_t _triggerEventUINT8Reliable_ReqArg3, CommonAPI::CallStatus &_internalCallStatus);



 private:
    std::shared_ptr< ETSProxyBase> delegate_;
};

typedef ETSProxy<> ETSProxyDefault;

namespace ETSExtensions {
    /*
     * description: 
     * A field for notifying version information.
     */
    template <template <typename > class _ExtensionType>
    class ETSInterfaceVersionAttributeExtension {
     public:
        typedef _ExtensionType< ETSProxyBase::ETSInterfaceVersionAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ETSProxyBase::ETSInterfaceVersionAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ETSInterfaceVersionAttributeExtension(ETSProxyBase& proxy): attributeExtension_(proxy.getETSInterfaceVersionAttribute()) {
        }
    
        inline extension_type& getETSInterfaceVersionAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    /*
     * description: 
     * A field of UINT8 type.
     */
    template <template <typename > class _ExtensionType>
    class TestFieldUINT8AttributeExtension {
     public:
        typedef _ExtensionType< ETSProxyBase::TestFieldUINT8Attribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ETSProxyBase::TestFieldUINT8Attribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        TestFieldUINT8AttributeExtension(ETSProxyBase& proxy): attributeExtension_(proxy.getTestFieldUINT8Attribute()) {
        }
    
        inline extension_type& getTestFieldUINT8AttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    /*
     * description: 
     * A field of UINT8 array.
     */
    template <template <typename > class _ExtensionType>
    class TestFieldUINT8ArrayAttributeExtension {
     public:
        typedef _ExtensionType< ETSProxyBase::TestFieldUINT8ArrayAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ETSProxyBase::TestFieldUINT8ArrayAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        TestFieldUINT8ArrayAttributeExtension(ETSProxyBase& proxy): attributeExtension_(proxy.getTestFieldUINT8ArrayAttribute()) {
        }
    
        inline extension_type& getTestFieldUINT8ArrayAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    /*
     * description: 
     * A field of UINT8 type over reliable endpoint.
     */
    template <template <typename > class _ExtensionType>
    class TestFieldUINT8ReliableAttributeExtension {
     public:
        typedef _ExtensionType< ETSProxyBase::TestFieldUINT8ReliableAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ETSProxyBase::TestFieldUINT8ReliableAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        TestFieldUINT8ReliableAttributeExtension(ETSProxyBase& proxy): attributeExtension_(proxy.getTestFieldUINT8ReliableAttribute()) {
        }
    
        inline extension_type& getTestFieldUINT8ReliableAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace ETSExtensions

//
// ETSProxy Implementation
//
template <typename ... _AttributeExtensions>
ETSProxy<_AttributeExtensions...>::ETSProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ETSProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ETSProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ETSProxy<_AttributeExtensions...>::~ETSProxy() {
}

/*
 * description: 
 * Check byte order handling of parameters.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::checkByteOrder(uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_checkByteOrder_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->checkByteOrder(_checkByteOrder_ReqArg1, _checkByteOrder_ReqArg2, _internalCallStatus, _checkByteOrder_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::checkByteOrderAsync(const uint8_t &_checkByteOrder_ReqArg1, const uint16_t &_checkByteOrder_ReqArg2, CheckByteOrderAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->checkByteOrderAsync(_checkByteOrder_ReqArg1, _checkByteOrder_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Activates the remote client prxoy in the server side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceActivate(uint8_t _clientServiceActivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->clientServiceActivate(_clientServiceActivate_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Deactivates the remote client prxoy in the server side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceDeactivate(uint8_t _clientServiceDeactivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->clientServiceDeactivate(_clientServiceDeactivate_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Get last value of multicast event triggered by service running in client side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventUDPMulticast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPMulticast_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->clientServiceGetLastValueOfEventUDPMulticast(_internalCallStatus, _clientServiceGetLastValueOfEventUDPMulticast_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventUDPMulticastAsync(ClientServiceGetLastValueOfEventUDPMulticastAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->clientServiceGetLastValueOfEventUDPMulticastAsync(_callback, _info);
}
/*
 * description: 
 * Get last value of unicast event triggered by service launched in client side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventUDPUnicast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPUnicast_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->clientServiceGetLastValueOfEventUDPUnicast(_internalCallStatus, _clientServiceGetLastValueOfEventUDPUnicast_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventUDPUnicastAsync(ClientServiceGetLastValueOfEventUDPUnicastAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->clientServiceGetLastValueOfEventUDPUnicastAsync(_callback, _info);
}
/*
 * description: 
 * Subscribe to the event offered by service launched in client side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceSubscribeEventgroup(uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->clientServiceSubscribeEventgroup(_clientServiceSubscribeEventgroup_ReqArg1, _clientServiceSubscribeEventgroup_ReqArg2, _internalCallStatus);
}
/*
 * description: 
 * Reverse the bits of all the input parameters and return it back.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoBitfields(uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoBitfields_ResArg1, uint16_t &_echoBitfields_ResArg2, uint32_t &_echoBitfields_ResArg3, const CommonAPI::CallInfo *_info) {
    delegate_->echoBitfields(_echoBitfields_ReqArg1, _echoBitfields_ReqArg2, _echoBitfields_ReqArg3, _internalCallStatus, _echoBitfields_ResArg1, _echoBitfields_ResArg2, _echoBitfields_ResArg3, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoBitfieldsAsync(const uint8_t &_echoBitfields_ReqArg1, const uint16_t &_echoBitfields_ReqArg2, const uint32_t &_echoBitfields_ReqArg3, EchoBitfieldsAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoBitfieldsAsync(_echoBitfields_ReqArg1, _echoBitfields_ReqArg2, _echoBitfields_ReqArg3, _callback, _info);
}
/*
 * description: 
 * Returns the input parameters in reverse order.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoCommonDatatypes(bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, CommonAPI::CallStatus &_internalCallStatus, double &_EchoCommonDatatypes_ResArg1, float &_EchoCommonDatatypes_ResArg2, int32_t &_EchoCommonDatatypes_ResArg3, int16_t &_EchoCommonDatatypes_ResArg4, int8_t &_EchoCommonDatatypes_ResArg5, uint32_t &_EchoCommonDatatypes_ResArg6, uint16_t &_EchoCommonDatatypes_ResArg7, uint8_t &_EchoCommonDatatypes_ResArg8, bool &_EchoCommonDatatypes_ResArg9, const CommonAPI::CallInfo *_info) {
    delegate_->echoCommonDatatypes(_EchoCommonDatatypes_ReqArg1, _EchoCommonDatatypes_ReqArg2, _EchoCommonDatatypes_ReqArg3, _EchoCommonDatatypes_ReqArg4, _EchoCommonDatatypes_ReqArg5, _EchoCommonDatatypes_ReqArg6, _EchoCommonDatatypes_ReqArg7, _EchoCommonDatatypes_ReqArg8, _EchoCommonDatatypes_ReqArg9, _internalCallStatus, _EchoCommonDatatypes_ResArg1, _EchoCommonDatatypes_ResArg2, _EchoCommonDatatypes_ResArg3, _EchoCommonDatatypes_ResArg4, _EchoCommonDatatypes_ResArg5, _EchoCommonDatatypes_ResArg6, _EchoCommonDatatypes_ResArg7, _EchoCommonDatatypes_ResArg8, _EchoCommonDatatypes_ResArg9, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoCommonDatatypesAsync(const bool &_EchoCommonDatatypes_ReqArg1, const uint8_t &_EchoCommonDatatypes_ReqArg2, const uint16_t &_EchoCommonDatatypes_ReqArg3, const uint32_t &_EchoCommonDatatypes_ReqArg4, const int8_t &_EchoCommonDatatypes_ReqArg5, const int16_t &_EchoCommonDatatypes_ReqArg6, const int32_t &_EchoCommonDatatypes_ReqArg7, const float &_EchoCommonDatatypes_ReqArg8, const double &_EchoCommonDatatypes_ReqArg9, EchoCommonDatatypesAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoCommonDatatypesAsync(_EchoCommonDatatypes_ReqArg1, _EchoCommonDatatypes_ReqArg2, _EchoCommonDatatypes_ReqArg3, _EchoCommonDatatypes_ReqArg4, _EchoCommonDatatypes_ReqArg5, _EchoCommonDatatypes_ReqArg6, _EchoCommonDatatypes_ReqArg7, _EchoCommonDatatypes_ReqArg8, _EchoCommonDatatypes_ReqArg9, _callback, _info);
}
/*
 * description: 
 * Returns back the ENUM passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoENUM(ETS::Enum _echoENUM_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, ETS::Enum &_echoENUM_ResArg1, const CommonAPI::CallInfo *_info) {
    if (!_echoENUM_ReqArg1.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->echoENUM(_echoENUM_ReqArg1, _internalCallStatus, _echoENUM_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoENUMAsync(const ETS::Enum &_echoENUM_ReqArg1, EchoENUMAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_echoENUM_ReqArg1.validate()) {
        ETS::Enum echoENUM_ResArg1 = ETS::Enum::UNKNOWN;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, echoENUM_ResArg1);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->echoENUMAsync(_echoENUM_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the double passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoFLOAT64(double _echoFLOAT64_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, double &_echoFLOAT64_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoFLOAT64(_echoFLOAT64_ReqArg1, _internalCallStatus, _echoFLOAT64_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoFLOAT64Async(const double &_echoFLOAT64_ReqArg1, EchoFLOAT64AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoFLOAT64Async(_echoFLOAT64_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the int8 passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoINT8(int8_t _echoINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, int8_t &_echoINT8_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoINT8(_echoINT8_ReqArg1, _internalCallStatus, _echoINT8_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoINT8Async(const int8_t &_echoINT8_ReqArg1, EchoINT8AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoINT8Async(_echoINT8_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the static array of uint8 passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoStaticUINT8Array(std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_echoStaticUINT8Array_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoStaticUINT8Array(_echoStaticUINT8Array_ReqArg1, _internalCallStatus, _echoStaticUINT8Array_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoStaticUINT8ArrayAsync(const std::vector< uint8_t > &_echoStaticUINT8Array_ReqArg1, EchoStaticUINT8ArrayAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoStaticUINT8ArrayAsync(_echoStaticUINT8Array_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the uint8 passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8(uint8_t _echoUINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8(_echoUINT8_ReqArg1, _internalCallStatus, _echoUINT8_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8Async(const uint8_t &_echoUINT8_ReqArg1, EchoUINT8AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8Async(_echoUINT8_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the array of uint8 passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8Array(uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array_ResArg1, std::vector< uint8_t > &_echoUINT8Array_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8Array(_echoUINT8Array_ReqArg1, _echoUINT8Array_ReqArg2, _internalCallStatus, _echoUINT8Array_ResArg1, _echoUINT8Array_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8ArrayAsync(const uint32_t &_echoUINT8Array_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array_ReqArg2, EchoUINT8ArrayAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8ArrayAsync(_echoUINT8Array_ReqArg1, _echoUINT8Array_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the input array of uint8 having 16th bit length field.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8Array16BitLength(uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8Array16BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array16BitLength_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8Array16BitLength(_echoUINT8Array16BitLength_ReqArg1, _echoUINT8Array16BitLength_ReqArg2, _internalCallStatus, _echoUINT8Array16BitLength_ResArg1, _echoUINT8Array16BitLength_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8Array16BitLengthAsync(const uint16_t &_echoUINT8Array16BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array16BitLength_ReqArg2, EchoUINT8Array16BitLengthAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8Array16BitLengthAsync(_echoUINT8Array16BitLength_ReqArg1, _echoUINT8Array16BitLength_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the 2D-array of uint8 passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8Array2Dim(uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array2Dim_ResArg1, std::vector< ETS::uint8ArrayReturnArray > &_echoUINT8Array2Dim_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8Array2Dim(_echoUINT8Array2Dim_ReqArg1, _echoUINT8Array2Dim_ReqArg2, _internalCallStatus, _echoUINT8Array2Dim_ResArg1, _echoUINT8Array2Dim_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8Array2DimAsync(const uint32_t &_echoUINT8Array2Dim_ReqArg1, const std::vector< ETS::uint8ArrayArray > &_echoUINT8Array2Dim_ReqArg2, EchoUINT8Array2DimAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8Array2DimAsync(_echoUINT8Array2Dim_ReqArg1, _echoUINT8Array2Dim_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the input array of uint8 having 8th bit length field.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8Array8BitLength(uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8Array8BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array8BitLength_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8Array8BitLength(_echoUINT8Array8BitLength_ReqArg1, _echoUINT8Array8BitLength_ReqArg2, _internalCallStatus, _echoUINT8Array8BitLength_ResArg1, _echoUINT8Array8BitLength_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8Array8BitLengthAsync(const uint8_t &_echoUINT8Array8BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array8BitLength_ReqArg2, EchoUINT8Array8BitLengthAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8Array8BitLengthAsync(_echoUINT8Array8BitLength_ReqArg1, _echoUINT8Array8BitLength_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the input array of uint8 having at least 3 entries back.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8ArrayMinSize(uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8ArrayMinSize_ResArg1, std::vector< uint8_t > &_echoUINT8ArrayMinSize_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8ArrayMinSize(_echoUINT8ArrayMinSize_ReqArg1, _echoUINT8ArrayMinSize_ReqArg2, _internalCallStatus, _echoUINT8ArrayMinSize_ResArg1, _echoUINT8ArrayMinSize_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8ArrayMinSizeAsync(const uint32_t &_echoUINT8ArrayMinSize_ReqArg1, const std::vector< uint8_t > &_echoUINT8ArrayMinSize_ReqArg2, EchoUINT8ArrayMinSizeAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8ArrayMinSizeAsync(_echoUINT8ArrayMinSize_ReqArg1, _echoUINT8ArrayMinSize_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the UTF16 string of dynamic length passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUTF16DYNAMIC(uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF16DYNAMIC_ResArg1, std::string &_echoUTF16DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUTF16DYNAMIC(_echoUTF16DYNAMIC_ReqArg1, _echoUTF16DYNAMIC_ReqArg2, _internalCallStatus, _echoUTF16DYNAMIC_ResArg1, _echoUTF16DYNAMIC_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUTF16DYNAMICAsync(const uint32_t &_echoUTF16DYNAMIC_ReqArg1, const std::string &_echoUTF16DYNAMIC_ReqArg2, EchoUTF16DYNAMICAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUTF16DYNAMICAsync(_echoUTF16DYNAMIC_ReqArg1, _echoUTF16DYNAMIC_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the UTF16 string of fixed length passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUTF16FIXED(std::string _echoUTF16FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF16FIXED_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUTF16FIXED(_echoUTF16FIXED_ReqArg1, _internalCallStatus, _echoUTF16FIXED_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUTF16FIXEDAsync(const std::string &_echoUTF16FIXED_ReqArg1, EchoUTF16FIXEDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUTF16FIXEDAsync(_echoUTF16FIXED_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Returns back the UTF8 string of dynamic length passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUTF8DYNAMIC(uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF8DYNAMIC_ResArg1, std::string &_echoUTF8DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info) {
    delegate_->echoUTF8DYNAMIC(_echoUTF8DYNAMIC_ReqArg1, _echoUTF8DYNAMIC_ReqArg2, _internalCallStatus, _echoUTF8DYNAMIC_ResArg1, _echoUTF8DYNAMIC_ResArg2, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUTF8DYNAMICAsync(const uint32_t &_echoUTF8DYNAMIC_ReqArg1, const std::string &_echoUTF8DYNAMIC_ReqArg2, EchoUTF8DYNAMICAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUTF8DYNAMICAsync(_echoUTF8DYNAMIC_ReqArg1, _echoUTF8DYNAMIC_ReqArg2, _callback, _info);
}
/*
 * description: 
 * Returns back the UTF8 string of fixed length passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUTF8FIXED(std::string _echoUTF8FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF8FIXED_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUTF8FIXED(_echoUTF8FIXED_ReqArg1, _internalCallStatus, _echoUTF8FIXED_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUTF8FIXEDAsync(const std::string &_echoUTF8FIXED_ReqArg1, EchoUTF8FIXEDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUTF8FIXEDAsync(_echoUTF8FIXED_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Reset interface to default values.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::resetInterface(CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->resetInterface(_internalCallStatus);
}
/*
 * description: 
 * Suspend inteface by stopping offer and resume afterwards.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::suspendInterface(uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->suspendInterface(_suspendInterface_ReqArg1, _suspendInterface_ReqArg2, _internalCallStatus);
}
/*
 * description: 
 * Requests to trigger an broadcast event of type uint8.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8(uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8(_triggerEventUINT8_ReqArg1, _triggerEventUINT8_ReqArg2, _triggerEventUINT8_ReqArg3, _internalCallStatus);
}
/*
 * description: 
 * Requests to trigger an broadcast event of type array of uint8.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8Array(uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8Array(_triggerEventUINT8Array_ReqArg1, _triggerEventUINT8Array_ReqArg2, _triggerEventUINT8Array_ReqArg3, _internalCallStatus);
}
/*
 * description: 
 * Requests to trigger an broadcast event of e2e data.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8E2E(uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8E2E(_triggerEventUINT8E2E_ReqArg1, _triggerEventUINT8E2E_ReqArg2, _triggerEventUINT8E2E_ReqArg3, _internalCallStatus);
}
/*
 * description: 
 * Requests to trigger an broadcast event of multicast type.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8Multicast(uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8Multicast(_triggerEventUINT8Multicast_ReqArg1, _triggerEventUINT8Multicast_ReqArg2, _triggerEventUINT8Multicast_ReqArg3, _internalCallStatus);
}
/*
 * description: 
 * Returns back the e2e data passed as input parameter.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8E2E(uint16_t _echoUINT8E2E_ReqArg1, uint16_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8E2E_ResArg1, uint16_t &_echoUINT8E2E_ResArg2, uint32_t &_echoUINT8E2E_ResArg3, uint32_t &_echoUINT8E2E_ResArg4, uint8_t &_echoUINT8E2E_ResArg5, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8E2E(_echoUINT8E2E_ReqArg1, _echoUINT8E2E_ReqArg2, _echoUINT8E2E_ReqArg3, _echoUINT8E2E_ReqArg4, _echoUINT8E2E_ReqArg5, _internalCallStatus, _echoUINT8E2E_ResArg1, _echoUINT8E2E_ResArg2, _echoUINT8E2E_ResArg3, _echoUINT8E2E_ResArg4, _echoUINT8E2E_ResArg5, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8E2EAsync(const uint16_t &_echoUINT8E2E_ReqArg1, const uint16_t &_echoUINT8E2E_ReqArg2, const uint32_t &_echoUINT8E2E_ReqArg3, const uint32_t &_echoUINT8E2E_ReqArg4, const uint8_t &_echoUINT8E2E_ReqArg5, EchoUINT8E2EAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8E2EAsync(_echoUINT8E2E_ReqArg1, _echoUINT8E2E_ReqArg2, _echoUINT8E2E_ReqArg3, _echoUINT8E2E_ReqArg4, _echoUINT8E2E_ReqArg5, _callback, _info);
}
/*
 * description: 
 * Sends the uint8 array over SOME/IP TP.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8ArrayLengthTP(_inUINT8Array_ReqArg1, _internalCallStatus, _outUINT8Array_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthTPAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8ArrayLengthTPAsync(_inUINT8Array_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Sends the uint8 array as input over SOME/IP TP.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthInTP(std::vector< uint8_t > _inUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8ArrayLengthInTP(_inUINT8Array_ReqArg1, _internalCallStatus, _outUINT32_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthInTPAsync(const std::vector< uint8_t > &_inUINT8Array_ReqArg1, EchoUINT8ArrayLengthInTPAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8ArrayLengthInTPAsync(_inUINT8Array_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Sends the uint8 array as reply over SOME/IP TP.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthOutTP(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_outUINT8Array_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8ArrayLengthOutTP(_inUINT32_ReqArg1, _internalCallStatus, _outUINT8Array_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthOutTPAsync(const uint32_t &_inUINT32_ReqArg1, EchoUINT8ArrayLengthOutTPAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8ArrayLengthOutTPAsync(_inUINT32_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Sends the uint8 array as input over SOME/IP TP.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8ArrayLengthTPNoResponse(std::vector< uint8_t > _echoUINT8ArrayLengthTPNoResponse_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->echoUINT8ArrayLengthTPNoResponse(_echoUINT8ArrayLengthTPNoResponse_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Requests to triggers an TP Event of type uint8 array.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8ArrayTP(std::vector< uint8_t > _triggerEventUINT8ArrayTP_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8ArrayTP(_triggerEventUINT8ArrayTP_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Requests to triggers an TP Event of type uint8 array.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8ArrayTPNoReqTPPayload(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8ArrayTPNoReqTPPayload(_triggerEventUINT32_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Requests to triggers an periodic event of type uint32.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT32Periodic(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT32Periodic(_triggerEventUINT32_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Requests to triggers an on change event of type uint32.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT32UpdateOnChange(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT32UpdateOnChange(_triggerEventUINT32_ReqArg1, _internalCallStatus);
}
/*
 * description: 
 * Activates Test Service in the server side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::activateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->activateTestSerivce(_activateTestSerivce_ReqArg1, _activateTestSerivce_ReqArg2, _internalCallStatus);
}
/*
 * description: 
 * Deactivates Test Service in the server side.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::deactivateTestSerivce(uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->deactivateTestSerivce(_activateTestSerivce_ReqArg1, _activateTestSerivce_ReqArg2, _internalCallStatus);
}
/*
 * description: 
 * The method returns the transfered UINT8 value back to the invoker over reliable endpoint.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::echoUINT8RELIABLE(uint8_t _echoUINT8RELIABLE_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8RELIABLE_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT8RELIABLE(_echoUINT8RELIABLE_ReqArg1, _internalCallStatus, _echoUINT8RELIABLE_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::echoUINT8RELIABLEAsync(const uint8_t &_echoUINT8RELIABLE_ReqArg1, EchoUINT8RELIABLEAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT8RELIABLEAsync(_echoUINT8RELIABLE_ReqArg1, _callback, _info);
}
/*
 * description: 
 * Get last value of TestEventUINT8Reliable.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventTCP(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventTCP_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->clientServiceGetLastValueOfEventTCP(_internalCallStatus, _clientServiceGetLastValueOfEventTCP_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSProxy<_AttributeExtensions...>::clientServiceGetLastValueOfEventTCPAsync(ClientServiceGetLastValueOfEventTCPAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->clientServiceGetLastValueOfEventTCPAsync(_callback, _info);
}
/*
 * description: 
 * Requests to trigger an broadcast event of type uint8 over reliable endpoint.
 */
template <typename ... _AttributeExtensions>
void ETSProxy<_AttributeExtensions...>::triggerEventUINT8Reliable(uint32_t _triggerEventUINT8Reliable_ReqArg1, uint32_t _triggerEventUINT8Reliable_ReqArg2, uint32_t _triggerEventUINT8Reliable_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) {
    delegate_->triggerEventUINT8Reliable(_triggerEventUINT8Reliable_ReqArg1, _triggerEventUINT8Reliable_ReqArg2, _triggerEventUINT8Reliable_ReqArg3, _internalCallStatus);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ETSProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ETSProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ETSProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ETSProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ETSProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ETSProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace testability
} // namespace someip
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::someip::testability::ETSProxy,
    _AttributeExtension> {
    typedef typename ::v1::someip::testability::ETSProxy<
            ::v1::someip::testability::ETSExtensions::ETSInterfaceVersionAttributeExtension<_AttributeExtension>, 
            ::v1::someip::testability::ETSExtensions::TestFieldUINT8AttributeExtension<_AttributeExtension>, 
            ::v1::someip::testability::ETSExtensions::TestFieldUINT8ArrayAttributeExtension<_AttributeExtension>, 
            ::v1::someip::testability::ETSExtensions::TestFieldUINT8ReliableAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_PROXY_HPP_
