/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_SOMEIP_TESTABILITY_ETS_PROXY_BASE_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_PROXY_BASE_HPP_

#include <v1/someip/testability/ETS.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

class ETSProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        uint8_t
    > TestEventUINT8Event;
    typedef CommonAPI::Event<
        std::vector< uint8_t >
    > TestEventUINT8ArrayEvent;
    typedef CommonAPI::Event<
        uint16_t, uint16_t, uint32_t, uint32_t, uint8_t
    > TestEventUINT8E2EEvent;
    typedef CommonAPI::Event<
        uint8_t
    > TestEventUINT8MulticastEvent;
    typedef CommonAPI::Event<
        std::vector< uint8_t >
    > TestEventUINT8TPEvent;
    typedef CommonAPI::Event<
        uint32_t
    > TestEventUINT32PeriodicEvent;
    typedef CommonAPI::Event<
        uint32_t
    > TestEventUINT32UpdateOnChangeEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&)> CheckByteOrderAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&)> ClientServiceGetLastValueOfEventUDPMulticastAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&)> ClientServiceGetLastValueOfEventUDPUnicastAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&, const uint16_t&, const uint32_t&)> EchoBitfieldsAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const double&, const float&, const int32_t&, const int16_t&, const int8_t&, const uint32_t&, const uint16_t&, const uint8_t&, const bool&)> EchoCommonDatatypesAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ETS::Enum&)> EchoENUMAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const double&)> EchoFLOAT64AsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const int8_t&)> EchoINT8AsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::vector< uint8_t >&)> EchoStaticUINT8ArrayAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&)> EchoUINT8AsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const std::vector< uint8_t >&)> EchoUINT8ArrayAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint16_t&, const std::vector< uint8_t >&)> EchoUINT8Array16BitLengthAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const std::vector< ETS::uint8ArrayReturnArray >&)> EchoUINT8Array2DimAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&, const std::vector< uint8_t >&)> EchoUINT8Array8BitLengthAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const std::vector< uint8_t >&)> EchoUINT8ArrayMinSizeAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const std::string&)> EchoUTF16DYNAMICAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> EchoUTF16FIXEDAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const std::string&)> EchoUTF8DYNAMICAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> EchoUTF8FIXEDAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint32_t&, const uint32_t&, const uint32_t&, const uint32_t&, const uint8_t&)> EchoUINT8E2EAsyncCallback;

    /*
     * description: 
     * Check byte order handling of parameters.
     */
    virtual void checkByteOrder(uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_checkByteOrder_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> checkByteOrderAsync(const uint8_t &_checkByteOrder_ReqArg1, const uint16_t &_checkByteOrder_ReqArg2, CheckByteOrderAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Activates the remote client prxoy in the server side.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void clientServiceActivate(uint8_t _clientServiceActivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Deactivates the remote client prxoy in the server side.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void clientServiceDeactivate(uint8_t _clientServiceDeactivate_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     */
    virtual void clientServiceGetLastValueOfEventUDPMulticast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPMulticast_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPMulticastAsync(ClientServiceGetLastValueOfEventUDPMulticastAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     */
    virtual void clientServiceGetLastValueOfEventUDPUnicast(CommonAPI::CallStatus &_internalCallStatus, uint8_t &_clientServiceGetLastValueOfEventUDPUnicast_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> clientServiceGetLastValueOfEventUDPUnicastAsync(ClientServiceGetLastValueOfEventUDPUnicastAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Subscribe to the event offered by service launched in client side.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void clientServiceSubscribeEventgroup(uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     */
    virtual void echoBitfields(uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoBitfields_ResArg1, uint16_t &_echoBitfields_ResArg2, uint32_t &_echoBitfields_ResArg3, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoBitfieldsAsync(const uint8_t &_echoBitfields_ReqArg1, const uint16_t &_echoBitfields_ReqArg2, const uint32_t &_echoBitfields_ReqArg3, EchoBitfieldsAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns the input parameters in reverse order.
     */
    virtual void echoCommonDatatypes(bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, CommonAPI::CallStatus &_internalCallStatus, double &_EchoCommonDatatypes_ResArg1, float &_EchoCommonDatatypes_ResArg2, int32_t &_EchoCommonDatatypes_ResArg3, int16_t &_EchoCommonDatatypes_ResArg4, int8_t &_EchoCommonDatatypes_ResArg5, uint32_t &_EchoCommonDatatypes_ResArg6, uint16_t &_EchoCommonDatatypes_ResArg7, uint8_t &_EchoCommonDatatypes_ResArg8, bool &_EchoCommonDatatypes_ResArg9, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoCommonDatatypesAsync(const bool &_EchoCommonDatatypes_ReqArg1, const uint8_t &_EchoCommonDatatypes_ReqArg2, const uint16_t &_EchoCommonDatatypes_ReqArg3, const uint32_t &_EchoCommonDatatypes_ReqArg4, const int8_t &_EchoCommonDatatypes_ReqArg5, const int16_t &_EchoCommonDatatypes_ReqArg6, const int32_t &_EchoCommonDatatypes_ReqArg7, const float &_EchoCommonDatatypes_ReqArg8, const double &_EchoCommonDatatypes_ReqArg9, EchoCommonDatatypesAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the ENUM passed as input parameter.
     */
    virtual void echoENUM(ETS::Enum _echoENUM_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, ETS::Enum &_echoENUM_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoENUMAsync(const ETS::Enum &_echoENUM_ReqArg1, EchoENUMAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the double passed as input parameter.
     */
    virtual void echoFLOAT64(double _echoFLOAT64_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, double &_echoFLOAT64_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoFLOAT64Async(const double &_echoFLOAT64_ReqArg1, EchoFLOAT64AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the int8 passed as input parameter.
     */
    virtual void echoINT8(int8_t _echoINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, int8_t &_echoINT8_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoINT8Async(const int8_t &_echoINT8_ReqArg1, EchoINT8AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     */
    virtual void echoStaticUINT8Array(std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::vector< uint8_t > &_echoStaticUINT8Array_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoStaticUINT8ArrayAsync(const std::vector< uint8_t > &_echoStaticUINT8Array_ReqArg1, EchoStaticUINT8ArrayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the uint8 passed as input parameter.
     */
    virtual void echoUINT8(uint8_t _echoUINT8_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8Async(const uint8_t &_echoUINT8_ReqArg1, EchoUINT8AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     */
    virtual void echoUINT8Array(uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array_ResArg1, std::vector< uint8_t > &_echoUINT8Array_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayAsync(const uint32_t &_echoUINT8Array_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array_ReqArg2, EchoUINT8ArrayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     */
    virtual void echoUINT8Array16BitLength(uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_echoUINT8Array16BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array16BitLength_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array16BitLengthAsync(const uint16_t &_echoUINT8Array16BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array16BitLength_ReqArg2, EchoUINT8Array16BitLengthAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     */
    virtual void echoUINT8Array2Dim(uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8Array2Dim_ResArg1, std::vector< ETS::uint8ArrayReturnArray > &_echoUINT8Array2Dim_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array2DimAsync(const uint32_t &_echoUINT8Array2Dim_ReqArg1, const std::vector< ETS::uint8ArrayArray > &_echoUINT8Array2Dim_ReqArg2, EchoUINT8Array2DimAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     */
    virtual void echoUINT8Array8BitLength(uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_echoUINT8Array8BitLength_ResArg1, std::vector< uint8_t > &_echoUINT8Array8BitLength_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8Array8BitLengthAsync(const uint8_t &_echoUINT8Array8BitLength_ReqArg1, const std::vector< uint8_t > &_echoUINT8Array8BitLength_ReqArg2, EchoUINT8Array8BitLengthAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     */
    virtual void echoUINT8ArrayMinSize(uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8ArrayMinSize_ResArg1, std::vector< uint8_t > &_echoUINT8ArrayMinSize_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8ArrayMinSizeAsync(const uint32_t &_echoUINT8ArrayMinSize_ReqArg1, const std::vector< uint8_t > &_echoUINT8ArrayMinSize_ReqArg2, EchoUINT8ArrayMinSizeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     */
    virtual void echoUTF16DYNAMIC(uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF16DYNAMIC_ResArg1, std::string &_echoUTF16DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUTF16DYNAMICAsync(const uint32_t &_echoUTF16DYNAMIC_ReqArg1, const std::string &_echoUTF16DYNAMIC_ReqArg2, EchoUTF16DYNAMICAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     */
    virtual void echoUTF16FIXED(std::string _echoUTF16FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF16FIXED_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUTF16FIXEDAsync(const std::string &_echoUTF16FIXED_ReqArg1, EchoUTF16FIXEDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     */
    virtual void echoUTF8DYNAMIC(uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUTF8DYNAMIC_ResArg1, std::string &_echoUTF8DYNAMIC_ResArg2, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUTF8DYNAMICAsync(const uint32_t &_echoUTF8DYNAMIC_ReqArg1, const std::string &_echoUTF8DYNAMIC_ReqArg2, EchoUTF8DYNAMICAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     */
    virtual void echoUTF8FIXED(std::string _echoUTF8FIXED_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, std::string &_echoUTF8FIXED_ResArg1, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUTF8FIXEDAsync(const std::string &_echoUTF8FIXED_ReqArg1, EchoUTF8FIXEDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Reset interface to default values.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void resetInterface(CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void suspendInterface(uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT8(uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT8Array(uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT8E2E(uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT8Multicast(uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
     */
    virtual TestEventUINT8Event& getTestEventUINT8Event() = 0;
    /*
     * description: 
     * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
     */
    virtual TestEventUINT8ArrayEvent& getTestEventUINT8ArrayEvent() = 0;
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
     */
    virtual TestEventUINT8E2EEvent& getTestEventUINT8E2EEvent() = 0;
    /*
     * description: 
     * Returns back the e2e data passed as input parameter.
     */
    virtual void echoUINT8E2E(uint32_t _echoUINT8E2E_ReqArg1, uint32_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_echoUINT8E2E_ResArg1, uint32_t &_echoUINT8E2E_ResArg2, uint32_t &_echoUINT8E2E_ResArg3, uint32_t &_echoUINT8E2E_ResArg4, uint8_t &_echoUINT8E2E_ResArg5, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> echoUINT8E2EAsync(const uint32_t &_echoUINT8E2E_ReqArg1, const uint32_t &_echoUINT8E2E_ReqArg2, const uint32_t &_echoUINT8E2E_ReqArg3, const uint32_t &_echoUINT8E2E_ReqArg4, const uint8_t &_echoUINT8E2E_ReqArg5, EchoUINT8E2EAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
     */
    virtual TestEventUINT8MulticastEvent& getTestEventUINT8MulticastEvent() = 0;
    /*
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void echoUINT8ArrayLengthTP(std::vector< uint8_t > _inUINT8Array, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * A broadcast TP event triggered on echoUINT8ArrayLengthTP method request.
     */
    virtual TestEventUINT8TPEvent& getTestEventUINT8TPEvent() = 0;
    /*
     * description: 
     * Requests to triggers an periodic event of type uint32.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT32Periodic(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
     */
    virtual TestEventUINT32PeriodicEvent& getTestEventUINT32PeriodicEvent() = 0;
    /*
     * description: 
     * Requests to triggers an on change event of type uint32.
     */
    /**
     * @invariant Fire And Forget
     */
    virtual void triggerEventUINT32UpdateOnChange(uint32_t _triggerEventUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus) = 0;
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
     */
    virtual TestEventUINT32UpdateOnChangeEvent& getTestEventUINT32UpdateOnChangeEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace testability
} // namespace someip
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_PROXY_BASE_HPP_
