/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * Testability Service to be activated on client side on clientServiceActivate request.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_BASE_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_BASE_HPP_

#include <v1/someip/testability/ETSSecondaryService.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

class ETSSecondaryServiceProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        uint8_t
    > SecondaryEventUINT8Event;
    typedef CommonAPI::Event<
        uint8_t
    > SecondaryMulticastEventUINT8Event;


    /*
     * description: 
     * A broadcast event to support clientServiceSubscribeEventgroup request.
     */
    virtual SecondaryEventUINT8Event& getSecondaryEventUINT8Event() = 0;
    /*
     * description: 
     * A broadcast event of type multicast to support clientServiceSubscribeEventgroup request.
     */
    virtual SecondaryMulticastEventUINT8Event& getSecondaryMulticastEventUINT8Event() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace testability
} // namespace someip
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_BASE_HPP_
