/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_SOMEIP_TESTABILITY_ETS_STUB_DEFAULT_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/someip/testability/ETSStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace someip {
namespace testability {

/**
 * Provides a default implementation for ETSStubRemoteEvent and
 * ETSStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT ETSStubDefault
    : public virtual ETSStub {
public:
    COMMONAPI_EXPORT ETSStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(ETS::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT ETSStubRemoteEvent* initStubAdapter(const std::shared_ptr< ETSStubAdapter> &_adapter) {
        CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * Check byte order handling of parameters.
     */
    COMMONAPI_EXPORT virtual void checkByteOrder(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, checkByteOrderReply_t _reply) {
        (void)_client;
        (void)_checkByteOrder_ReqArg1;
        (void)_checkByteOrder_ReqArg2;
        uint32_t checkByteOrder_ResArg1 = 0ul;
        _reply(checkByteOrder_ResArg1);
    }
    /*
     * description: 
     * Activates the remote client prxoy in the server side.
     */
    COMMONAPI_EXPORT virtual void clientServiceActivate(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _clientServiceActivate_ReqArg1) {
        (void)_client;
        (void)_clientServiceActivate_ReqArg1;
    }
    /*
     * description: 
     * Deactivates the remote client prxoy in the server side.
     */
    COMMONAPI_EXPORT virtual void clientServiceDeactivate(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _clientServiceDeactivate_ReqArg1) {
        (void)_client;
        (void)_clientServiceDeactivate_ReqArg1;
    }
    /*
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     */
    COMMONAPI_EXPORT virtual void clientServiceGetLastValueOfEventUDPMulticast(const std::shared_ptr<CommonAPI::ClientId> _client, clientServiceGetLastValueOfEventUDPMulticastReply_t _reply) {
        (void)_client;
        uint8_t clientServiceGetLastValueOfEventUDPMulticast_ResArg1 = 0u;
        _reply(clientServiceGetLastValueOfEventUDPMulticast_ResArg1);
    }
    /*
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     */
    COMMONAPI_EXPORT virtual void clientServiceGetLastValueOfEventUDPUnicast(const std::shared_ptr<CommonAPI::ClientId> _client, clientServiceGetLastValueOfEventUDPUnicastReply_t _reply) {
        (void)_client;
        uint8_t clientServiceGetLastValueOfEventUDPUnicast_ResArg1 = 0u;
        _reply(clientServiceGetLastValueOfEventUDPUnicast_ResArg1);
    }
    /*
     * description: 
     * Subscribe to the event offered by service launched in client side.
     */
    COMMONAPI_EXPORT virtual void clientServiceSubscribeEventgroup(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2) {
        (void)_client;
        (void)_clientServiceSubscribeEventgroup_ReqArg1;
        (void)_clientServiceSubscribeEventgroup_ReqArg2;
    }
    /*
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     */
    COMMONAPI_EXPORT virtual void echoBitfields(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, echoBitfieldsReply_t _reply) {
        (void)_client;
        (void)_echoBitfields_ReqArg1;
        (void)_echoBitfields_ReqArg2;
        (void)_echoBitfields_ReqArg3;
        uint8_t echoBitfields_ResArg1 = 0u;
        uint16_t echoBitfields_ResArg2 = 0u;
        uint32_t echoBitfields_ResArg3 = 0ul;
        _reply(echoBitfields_ResArg1, echoBitfields_ResArg2, echoBitfields_ResArg3);
    }
    /*
     * description: 
     * Returns the input parameters in reverse order.
     */
    COMMONAPI_EXPORT virtual void echoCommonDatatypes(const std::shared_ptr<CommonAPI::ClientId> _client, bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, echoCommonDatatypesReply_t _reply) {
        (void)_client;
        (void)_EchoCommonDatatypes_ReqArg1;
        (void)_EchoCommonDatatypes_ReqArg2;
        (void)_EchoCommonDatatypes_ReqArg3;
        (void)_EchoCommonDatatypes_ReqArg4;
        (void)_EchoCommonDatatypes_ReqArg5;
        (void)_EchoCommonDatatypes_ReqArg6;
        (void)_EchoCommonDatatypes_ReqArg7;
        (void)_EchoCommonDatatypes_ReqArg8;
        (void)_EchoCommonDatatypes_ReqArg9;
        double EchoCommonDatatypes_ResArg1 = 0.0;
        float EchoCommonDatatypes_ResArg2 = 0.0f;
        int32_t EchoCommonDatatypes_ResArg3 = 0;
        int16_t EchoCommonDatatypes_ResArg4 = 0;
        int8_t EchoCommonDatatypes_ResArg5 = 0;
        uint32_t EchoCommonDatatypes_ResArg6 = 0ul;
        uint16_t EchoCommonDatatypes_ResArg7 = 0u;
        uint8_t EchoCommonDatatypes_ResArg8 = 0u;
        bool EchoCommonDatatypes_ResArg9 = false;
        _reply(EchoCommonDatatypes_ResArg1, EchoCommonDatatypes_ResArg2, EchoCommonDatatypes_ResArg3, EchoCommonDatatypes_ResArg4, EchoCommonDatatypes_ResArg5, EchoCommonDatatypes_ResArg6, EchoCommonDatatypes_ResArg7, EchoCommonDatatypes_ResArg8, EchoCommonDatatypes_ResArg9);
    }
    /*
     * description: 
     * Returns back the ENUM passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoENUM(const std::shared_ptr<CommonAPI::ClientId> _client, ETS::Enum _echoENUM_ReqArg1, echoENUMReply_t _reply) {
        (void)_client;
        (void)_echoENUM_ReqArg1;
        ETS::Enum echoENUM_ResArg1 = ETS::Enum::UNKNOWN;
        if (!echoENUM_ResArg1.validate()) {
            return;
        }
        _reply(echoENUM_ResArg1);
    }
    /*
     * description: 
     * Returns back the double passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoFLOAT64(const std::shared_ptr<CommonAPI::ClientId> _client, double _echoFLOAT64_ReqArg1, echoFLOAT64Reply_t _reply) {
        (void)_client;
        (void)_echoFLOAT64_ReqArg1;
        double echoFLOAT64_ResArg1 = 0.0;
        _reply(echoFLOAT64_ResArg1);
    }
    /*
     * description: 
     * Returns back the int8 passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoINT8(const std::shared_ptr<CommonAPI::ClientId> _client, int8_t _echoINT8_ReqArg1, echoINT8Reply_t _reply) {
        (void)_client;
        (void)_echoINT8_ReqArg1;
        int8_t echoINT8_ResArg1 = 0;
        _reply(echoINT8_ResArg1);
    }
    /*
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoStaticUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, echoStaticUINT8ArrayReply_t _reply) {
        (void)_client;
        (void)_echoStaticUINT8Array_ReqArg1;
        std::vector< uint8_t > echoStaticUINT8Array_ResArg1 = {};
        _reply(echoStaticUINT8Array_ResArg1);
    }
    /*
     * description: 
     * Returns back the uint8 passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUINT8(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoUINT8_ReqArg1, echoUINT8Reply_t _reply) {
        (void)_client;
        (void)_echoUINT8_ReqArg1;
        uint8_t echoUINT8_ResArg1 = 0u;
        _reply(echoUINT8_ResArg1);
    }
    /*
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, echoUINT8ArrayReply_t _reply) {
        (void)_client;
        (void)_echoUINT8Array_ReqArg1;
        (void)_echoUINT8Array_ReqArg2;
        uint32_t echoUINT8Array_ResArg1 = 0ul;
        std::vector< uint8_t > echoUINT8Array_ResArg2 = {};
        _reply(echoUINT8Array_ResArg1, echoUINT8Array_ResArg2);
    }
    /*
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     */
    COMMONAPI_EXPORT virtual void echoUINT8Array16BitLength(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, echoUINT8Array16BitLengthReply_t _reply) {
        (void)_client;
        (void)_echoUINT8Array16BitLength_ReqArg1;
        (void)_echoUINT8Array16BitLength_ReqArg2;
        uint16_t echoUINT8Array16BitLength_ResArg1 = 0u;
        std::vector< uint8_t > echoUINT8Array16BitLength_ResArg2 = {};
        _reply(echoUINT8Array16BitLength_ResArg1, echoUINT8Array16BitLength_ResArg2);
    }
    /*
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUINT8Array2Dim(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, echoUINT8Array2DimReply_t _reply) {
        (void)_client;
        (void)_echoUINT8Array2Dim_ReqArg1;
        (void)_echoUINT8Array2Dim_ReqArg2;
        uint32_t echoUINT8Array2Dim_ResArg1 = 0ul;
        std::vector< ETS::uint8ArrayReturnArray > echoUINT8Array2Dim_ResArg2 = {};
        _reply(echoUINT8Array2Dim_ResArg1, echoUINT8Array2Dim_ResArg2);
    }
    /*
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     */
    COMMONAPI_EXPORT virtual void echoUINT8Array8BitLength(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, echoUINT8Array8BitLengthReply_t _reply) {
        (void)_client;
        (void)_echoUINT8Array8BitLength_ReqArg1;
        (void)_echoUINT8Array8BitLength_ReqArg2;
        uint8_t echoUINT8Array8BitLength_ResArg1 = 0u;
        std::vector< uint8_t > echoUINT8Array8BitLength_ResArg2 = {};
        _reply(echoUINT8Array8BitLength_ResArg1, echoUINT8Array8BitLength_ResArg2);
    }
    /*
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     */
    COMMONAPI_EXPORT virtual void echoUINT8ArrayMinSize(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, echoUINT8ArrayMinSizeReply_t _reply) {
        (void)_client;
        (void)_echoUINT8ArrayMinSize_ReqArg1;
        (void)_echoUINT8ArrayMinSize_ReqArg2;
        uint32_t echoUINT8ArrayMinSize_ResArg1 = 0ul;
        std::vector< uint8_t > echoUINT8ArrayMinSize_ResArg2 = {};
        _reply(echoUINT8ArrayMinSize_ResArg1, echoUINT8ArrayMinSize_ResArg2);
    }
    /*
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUTF16DYNAMIC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, echoUTF16DYNAMICReply_t _reply) {
        (void)_client;
        (void)_echoUTF16DYNAMIC_ReqArg1;
        (void)_echoUTF16DYNAMIC_ReqArg2;
        uint32_t echoUTF16DYNAMIC_ResArg1 = 0ul;
        std::string echoUTF16DYNAMIC_ResArg2 = "";
        _reply(echoUTF16DYNAMIC_ResArg1, echoUTF16DYNAMIC_ResArg2);
    }
    /*
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUTF16FIXED(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _echoUTF16FIXED_ReqArg1, echoUTF16FIXEDReply_t _reply) {
        (void)_client;
        (void)_echoUTF16FIXED_ReqArg1;
        std::string echoUTF16FIXED_ResArg1 = "";
        _reply(echoUTF16FIXED_ResArg1);
    }
    /*
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUTF8DYNAMIC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, echoUTF8DYNAMICReply_t _reply) {
        (void)_client;
        (void)_echoUTF8DYNAMIC_ReqArg1;
        (void)_echoUTF8DYNAMIC_ReqArg2;
        uint32_t echoUTF8DYNAMIC_ResArg1 = 0ul;
        std::string echoUTF8DYNAMIC_ResArg2 = "";
        _reply(echoUTF8DYNAMIC_ResArg1, echoUTF8DYNAMIC_ResArg2);
    }
    /*
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUTF8FIXED(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _echoUTF8FIXED_ReqArg1, echoUTF8FIXEDReply_t _reply) {
        (void)_client;
        (void)_echoUTF8FIXED_ReqArg1;
        std::string echoUTF8FIXED_ResArg1 = "";
        _reply(echoUTF8FIXED_ResArg1);
    }
    /*
     * description: 
     * Reset interface to default values.
     */
    COMMONAPI_EXPORT virtual void resetInterface(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
    }
    /*
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     */
    COMMONAPI_EXPORT virtual void suspendInterface(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2) {
        (void)_client;
        (void)_suspendInterface_ReqArg1;
        (void)_suspendInterface_ReqArg2;
    }
    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3) {
        (void)_client;
        (void)_triggerEventUINT8_ReqArg1;
        (void)_triggerEventUINT8_ReqArg2;
        (void)_triggerEventUINT8_ReqArg3;
    }
    /*
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3) {
        (void)_client;
        (void)_triggerEventUINT8Array_ReqArg1;
        (void)_triggerEventUINT8Array_ReqArg2;
        (void)_triggerEventUINT8Array_ReqArg3;
    }
    /*
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8E2E(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3) {
        (void)_client;
        (void)_triggerEventUINT8E2E_ReqArg1;
        (void)_triggerEventUINT8E2E_ReqArg2;
        (void)_triggerEventUINT8E2E_ReqArg3;
    }
    /*
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8Multicast(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3) {
        (void)_client;
        (void)_triggerEventUINT8Multicast_ReqArg1;
        (void)_triggerEventUINT8Multicast_ReqArg2;
        (void)_triggerEventUINT8Multicast_ReqArg3;
    }
    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT8Event(const uint8_t &_uINT8Value) {
        ETSStub::fireTestEventUINT8Event(_uINT8Value);
    }
    /*
     * description: 
     * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT8ArrayEvent(const std::vector< uint8_t > &_uINT8Array) {
        ETSStub::fireTestEventUINT8ArrayEvent(_uINT8Array);
    }
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT8E2EEvent(const uint16_t &_length, const uint16_t &_counter, const uint32_t &_dataID, const uint32_t &_CRC, const uint8_t &_uINT8Value) {
        ETSStub::fireTestEventUINT8E2EEvent(_length, _counter, _dataID, _CRC, _uINT8Value);
    }
    /*
     * description: 
     * Returns back the e2e data passed as input parameter.
     */
    COMMONAPI_EXPORT virtual void echoUINT8E2E(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _echoUINT8E2E_ReqArg1, uint16_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, echoUINT8E2EReply_t _reply) {
        (void)_client;
        (void)_echoUINT8E2E_ReqArg1;
        (void)_echoUINT8E2E_ReqArg2;
        (void)_echoUINT8E2E_ReqArg3;
        (void)_echoUINT8E2E_ReqArg4;
        (void)_echoUINT8E2E_ReqArg5;
        uint16_t echoUINT8E2E_ResArg1 = 0u;
        uint16_t echoUINT8E2E_ResArg2 = 0u;
        uint32_t echoUINT8E2E_ResArg3 = 0ul;
        uint32_t echoUINT8E2E_ResArg4 = 0ul;
        uint8_t echoUINT8E2E_ResArg5 = 0u;
        _reply(echoUINT8E2E_ResArg1, echoUINT8E2E_ResArg2, echoUINT8E2E_ResArg3, echoUINT8E2E_ResArg4, echoUINT8E2E_ResArg5);
    }
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT8MulticastEvent(const uint8_t &_uINT8Value) {
        ETSStub::fireTestEventUINT8MulticastEvent(_uINT8Value);
    }
    /*
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     */
    COMMONAPI_EXPORT virtual void echoUINT8ArrayLengthTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _inUINT8Array_ReqArg1, echoUINT8ArrayLengthTPReply_t _reply) {
        (void)_client;
        (void)_inUINT8Array_ReqArg1;
        std::vector< uint8_t > outUINT8Array_ResArg1 = {};
        _reply(outUINT8Array_ResArg1);
    }
    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    COMMONAPI_EXPORT virtual void echoUINT8ArrayLengthInTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _inUINT8Array_ReqArg1, echoUINT8ArrayLengthInTPReply_t _reply) {
        (void)_client;
        (void)_inUINT8Array_ReqArg1;
        uint32_t outUINT32_ResArg1 = 0ul;
        _reply(outUINT32_ResArg1);
    }
    /*
     * description: 
     * Sends the uint8 array as reply over SOME/IP TP.
     */
    COMMONAPI_EXPORT virtual void echoUINT8ArrayLengthOutTP(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _inUINT32_ReqArg1, echoUINT8ArrayLengthOutTPReply_t _reply) {
        (void)_client;
        (void)_inUINT32_ReqArg1;
        std::vector< uint8_t > outUINT8Array_ResArg1 = {};
        _reply(outUINT8Array_ResArg1);
    }
    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    COMMONAPI_EXPORT virtual void echoUINT8ArrayLengthTPNoResponse(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _echoUINT8ArrayLengthTPNoResponse_ReqArg1) {
        (void)_client;
        (void)_echoUINT8ArrayLengthTPNoResponse_ReqArg1;
    }
    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8ArrayTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _triggerEventUINT8ArrayTP_ReqArg1) {
        (void)_client;
        (void)_triggerEventUINT8ArrayTP_ReqArg1;
    }
    /*
     * description: 
     * A broadcast TP event triggered on triggerEventUINT8ArrayTP method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT8ArrayTPEvent(const std::vector< uint8_t > &_outUINT8EventArray) {
        ETSStub::fireTestEventUINT8ArrayTPEvent(_outUINT8EventArray);
    }
    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT8ArrayTPNoReqTPPayload(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) {
        (void)_client;
        (void)_triggerEventUINT32_ReqArg1;
    }
    /*
     * description: 
     * Requests to triggers an periodic event of type uint32.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT32Periodic(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) {
        (void)_client;
        (void)_triggerEventUINT32_ReqArg1;
    }
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT32PeriodicEvent(const uint32_t &_uINT32Value) {
        ETSStub::fireTestEventUINT32PeriodicEvent(_uINT32Value);
    }
    /*
     * description: 
     * Requests to triggers an on change event of type uint32.
     */
    COMMONAPI_EXPORT virtual void triggerEventUINT32UpdateOnChange(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) {
        (void)_client;
        (void)_triggerEventUINT32_ReqArg1;
    }
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
     */
    COMMONAPI_EXPORT virtual void fireTestEventUINT32UpdateOnChangeEvent(const uint32_t &_uINT32Value) {
        ETSStub::fireTestEventUINT32UpdateOnChangeEvent(_uINT32Value);
    }
    /*
     * description: 
     * Activates Test Service in the server side.
     */
    COMMONAPI_EXPORT virtual void activateTestSerivce(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2) {
        (void)_client;
        (void)_activateTestSerivce_ReqArg1;
        (void)_activateTestSerivce_ReqArg2;
    }
    /*
     * description: 
     * Deactivates Test Service in the server side.
     */
    COMMONAPI_EXPORT virtual void deactivateTestSerivce(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2) {
        (void)_client;
        (void)_activateTestSerivce_ReqArg1;
        (void)_activateTestSerivce_ReqArg2;
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual ETSStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(ETSStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        ETSStubDefault *defaultStub_;
    };
protected:
    ETSStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace testability
} // namespace someip
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_STUB_DEFAULT
