/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * Testability Service to be activated on client side on clientServiceActivate request.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_HPP_

#include <v1/someip/testability/ETSSecondaryServiceProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename ... _AttributeExtensions>
class ETSSecondaryServiceProxy
    : virtual public ETSSecondaryService,
      virtual public ETSSecondaryServiceProxyBase,
      virtual public _AttributeExtensions... {
public:
    ETSSecondaryServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ETSSecondaryServiceProxy();

    typedef ETSSecondaryService InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /*
     * description: 
     * A broadcast event to support clientServiceSubscribeEventgroup request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast SecondaryEventUINT8.
     */
    virtual SecondaryEventUINT8Event& getSecondaryEventUINT8Event() {
        return delegate_->getSecondaryEventUINT8Event();
    }
    /*
     * description: 
     * A broadcast event of type multicast to support clientServiceSubscribeEventgroup request.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast SecondaryMulticastEventUINT8.
     */
    virtual SecondaryMulticastEventUINT8Event& getSecondaryMulticastEventUINT8Event() {
        return delegate_->getSecondaryMulticastEventUINT8Event();
    }



 private:
    std::shared_ptr< ETSSecondaryServiceProxyBase> delegate_;
};

typedef ETSSecondaryServiceProxy<> ETSSecondaryServiceProxyDefault;


//
// ETSSecondaryServiceProxy Implementation
//
template <typename ... _AttributeExtensions>
ETSSecondaryServiceProxy<_AttributeExtensions...>::ETSSecondaryServiceProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ETSSecondaryServiceProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ETSSecondaryServiceProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ETSSecondaryServiceProxy<_AttributeExtensions...>::~ETSSecondaryServiceProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &ETSSecondaryServiceProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ETSSecondaryServiceProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ETSSecondaryServiceProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ETSSecondaryServiceProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ETSSecondaryServiceProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ETSSecondaryServiceProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace testability
} // namespace someip
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_Secondary_Service_PROXY_HPP_
