/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_SOMEIP_TESTABILITY_ETS_STUB_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/someip/testability/ETS.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service ETS. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class ETSStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual ETS {
 public:
    /**
    * Sends a broadcast event for TestEventUINT8. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT8Event(const uint8_t &_uINT8Value) = 0;
    /**
    * Sends a broadcast event for TestEventUINT8Array. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT8ArrayEvent(const std::vector< uint8_t > &_uINT8Array) = 0;
    /**
    * Sends a broadcast event for TestEventUINT8E2E. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT8E2EEvent(const uint16_t &_length, const uint16_t &_counter, const uint32_t &_dataID, const uint32_t &_CRC, const uint8_t &_uINT8Value) = 0;
    /**
    * Sends a broadcast event for TestEventUINT8Multicast. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT8MulticastEvent(const uint8_t &_uINT8Value) = 0;
    /**
    * Sends a broadcast event for TestEventUINT8ArrayTP. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT8ArrayTPEvent(const std::vector< uint8_t > &_outUINT8EventArray) = 0;
    /**
    * Sends a broadcast event for TestEventUINT32Periodic. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT32PeriodicEvent(const uint32_t &_uINT32Value) = 0;
    /**
    * Sends a broadcast event for TestEventUINT32UpdateOnChange. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireTestEventUINT32UpdateOnChangeEvent(const uint32_t &_uINT32Value) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for ETS.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ETSStubRemoteEvent
{
public:
    virtual ~ETSStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service ETS to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ETSStub
    : public virtual CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>
{
public:
    typedef std::function<void (uint32_t _checkByteOrder_ResArg1)> checkByteOrderReply_t;
    typedef std::function<void (uint8_t _clientServiceGetLastValueOfEventUDPMulticast_ResArg1)> clientServiceGetLastValueOfEventUDPMulticastReply_t;
    typedef std::function<void (uint8_t _clientServiceGetLastValueOfEventUDPUnicast_ResArg1)> clientServiceGetLastValueOfEventUDPUnicastReply_t;
    typedef std::function<void (uint8_t _echoBitfields_ResArg1, uint16_t _echoBitfields_ResArg2, uint32_t _echoBitfields_ResArg3)> echoBitfieldsReply_t;
    typedef std::function<void (double _EchoCommonDatatypes_ResArg1, float _EchoCommonDatatypes_ResArg2, int32_t _EchoCommonDatatypes_ResArg3, int16_t _EchoCommonDatatypes_ResArg4, int8_t _EchoCommonDatatypes_ResArg5, uint32_t _EchoCommonDatatypes_ResArg6, uint16_t _EchoCommonDatatypes_ResArg7, uint8_t _EchoCommonDatatypes_ResArg8, bool _EchoCommonDatatypes_ResArg9)> echoCommonDatatypesReply_t;
    typedef std::function<void (ETS::Enum _echoENUM_ResArg1)> echoENUMReply_t;
    typedef std::function<void (double _echoFLOAT64_ResArg1)> echoFLOAT64Reply_t;
    typedef std::function<void (int8_t _echoINT8_ResArg1)> echoINT8Reply_t;
    typedef std::function<void (std::vector< uint8_t > _echoStaticUINT8Array_ResArg1)> echoStaticUINT8ArrayReply_t;
    typedef std::function<void (uint8_t _echoUINT8_ResArg1)> echoUINT8Reply_t;
    typedef std::function<void (uint32_t _echoUINT8Array_ResArg1, std::vector< uint8_t > _echoUINT8Array_ResArg2)> echoUINT8ArrayReply_t;
    typedef std::function<void (uint16_t _echoUINT8Array16BitLength_ResArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ResArg2)> echoUINT8Array16BitLengthReply_t;
    typedef std::function<void (uint32_t _echoUINT8Array2Dim_ResArg1, std::vector< ETS::uint8ArrayReturnArray > _echoUINT8Array2Dim_ResArg2)> echoUINT8Array2DimReply_t;
    typedef std::function<void (uint8_t _echoUINT8Array8BitLength_ResArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ResArg2)> echoUINT8Array8BitLengthReply_t;
    typedef std::function<void (uint32_t _echoUINT8ArrayMinSize_ResArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ResArg2)> echoUINT8ArrayMinSizeReply_t;
    typedef std::function<void (uint32_t _echoUTF16DYNAMIC_ResArg1, std::string _echoUTF16DYNAMIC_ResArg2)> echoUTF16DYNAMICReply_t;
    typedef std::function<void (std::string _echoUTF16FIXED_ResArg1)> echoUTF16FIXEDReply_t;
    typedef std::function<void (uint32_t _echoUTF8DYNAMIC_ResArg1, std::string _echoUTF8DYNAMIC_ResArg2)> echoUTF8DYNAMICReply_t;
    typedef std::function<void (std::string _echoUTF8FIXED_ResArg1)> echoUTF8FIXEDReply_t;
    typedef std::function<void (uint16_t _echoUINT8E2E_ResArg1, uint16_t _echoUINT8E2E_ResArg2, uint32_t _echoUINT8E2E_ResArg3, uint32_t _echoUINT8E2E_ResArg4, uint8_t _echoUINT8E2E_ResArg5)> echoUINT8E2EReply_t;
    typedef std::function<void (std::vector< uint8_t > _outUINT8Array_ResArg1)> echoUINT8ArrayLengthTPReply_t;
    typedef std::function<void (uint32_t _outUINT32_ResArg1)> echoUINT8ArrayLengthInTPReply_t;
    typedef std::function<void (std::vector< uint8_t > _outUINT8Array_ResArg1)> echoUINT8ArrayLengthOutTPReply_t;

    virtual ~ETSStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 46);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * Check byte order handling of parameters.
     */
    /// This is the method that will be called on remote calls on the method checkByteOrder.
    virtual void checkByteOrder(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _checkByteOrder_ReqArg1, uint16_t _checkByteOrder_ReqArg2, checkByteOrderReply_t _reply) = 0;
    /*
     * description: 
     * Activates the remote client prxoy in the server side.
     */
    /// This is the method that will be called on remote calls on the method clientServiceActivate.
    virtual void clientServiceActivate(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _clientServiceActivate_ReqArg1) = 0;
    /*
     * description: 
     * Deactivates the remote client prxoy in the server side.
     */
    /// This is the method that will be called on remote calls on the method clientServiceDeactivate.
    virtual void clientServiceDeactivate(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _clientServiceDeactivate_ReqArg1) = 0;
    /*
     * description: 
     * Get last value of multicast event triggered by service running in client side.
     */
    /// This is the method that will be called on remote calls on the method clientServiceGetLastValueOfEventUDPMulticast.
    virtual void clientServiceGetLastValueOfEventUDPMulticast(const std::shared_ptr<CommonAPI::ClientId> _client, clientServiceGetLastValueOfEventUDPMulticastReply_t _reply) = 0;
    /*
     * description: 
     * Get last value of unicast event triggered by service launched in client side.
     */
    /// This is the method that will be called on remote calls on the method clientServiceGetLastValueOfEventUDPUnicast.
    virtual void clientServiceGetLastValueOfEventUDPUnicast(const std::shared_ptr<CommonAPI::ClientId> _client, clientServiceGetLastValueOfEventUDPUnicastReply_t _reply) = 0;
    /*
     * description: 
     * Subscribe to the event offered by service launched in client side.
     */
    /// This is the method that will be called on remote calls on the method clientServiceSubscribeEventgroup.
    virtual void clientServiceSubscribeEventgroup(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _clientServiceSubscribeEventgroup_ReqArg1, uint32_t _clientServiceSubscribeEventgroup_ReqArg2) = 0;
    /*
     * description: 
     * Reverse the bits of all the input parameters and return it back.
     */
    /// This is the method that will be called on remote calls on the method echoBitfields.
    virtual void echoBitfields(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoBitfields_ReqArg1, uint16_t _echoBitfields_ReqArg2, uint32_t _echoBitfields_ReqArg3, echoBitfieldsReply_t _reply) = 0;
    /*
     * description: 
     * Returns the input parameters in reverse order.
     */
    /// This is the method that will be called on remote calls on the method echoCommonDatatypes.
    virtual void echoCommonDatatypes(const std::shared_ptr<CommonAPI::ClientId> _client, bool _EchoCommonDatatypes_ReqArg1, uint8_t _EchoCommonDatatypes_ReqArg2, uint16_t _EchoCommonDatatypes_ReqArg3, uint32_t _EchoCommonDatatypes_ReqArg4, int8_t _EchoCommonDatatypes_ReqArg5, int16_t _EchoCommonDatatypes_ReqArg6, int32_t _EchoCommonDatatypes_ReqArg7, float _EchoCommonDatatypes_ReqArg8, double _EchoCommonDatatypes_ReqArg9, echoCommonDatatypesReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the ENUM passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoENUM.
    virtual void echoENUM(const std::shared_ptr<CommonAPI::ClientId> _client, ETS::Enum _echoENUM_ReqArg1, echoENUMReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the double passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoFLOAT64.
    virtual void echoFLOAT64(const std::shared_ptr<CommonAPI::ClientId> _client, double _echoFLOAT64_ReqArg1, echoFLOAT64Reply_t _reply) = 0;
    /*
     * description: 
     * Returns back the int8 passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoINT8.
    virtual void echoINT8(const std::shared_ptr<CommonAPI::ClientId> _client, int8_t _echoINT8_ReqArg1, echoINT8Reply_t _reply) = 0;
    /*
     * description: 
     * Returns back the static array of uint8 passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoStaticUINT8Array.
    virtual void echoStaticUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _echoStaticUINT8Array_ReqArg1, echoStaticUINT8ArrayReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the uint8 passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8.
    virtual void echoUINT8(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoUINT8_ReqArg1, echoUINT8Reply_t _reply) = 0;
    /*
     * description: 
     * Returns back the array of uint8 passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8Array.
    virtual void echoUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8Array_ReqArg1, std::vector< uint8_t > _echoUINT8Array_ReqArg2, echoUINT8ArrayReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having 16th bit length field.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8Array16BitLength.
    virtual void echoUINT8Array16BitLength(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _echoUINT8Array16BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array16BitLength_ReqArg2, echoUINT8Array16BitLengthReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the 2D-array of uint8 passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8Array2Dim.
    virtual void echoUINT8Array2Dim(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8Array2Dim_ReqArg1, std::vector< ETS::uint8ArrayArray > _echoUINT8Array2Dim_ReqArg2, echoUINT8Array2DimReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having 8th bit length field.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8Array8BitLength.
    virtual void echoUINT8Array8BitLength(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _echoUINT8Array8BitLength_ReqArg1, std::vector< uint8_t > _echoUINT8Array8BitLength_ReqArg2, echoUINT8Array8BitLengthReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the input array of uint8 having at least 3 entries back.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8ArrayMinSize.
    virtual void echoUINT8ArrayMinSize(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUINT8ArrayMinSize_ReqArg1, std::vector< uint8_t > _echoUINT8ArrayMinSize_ReqArg2, echoUINT8ArrayMinSizeReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the UTF16 string of dynamic length passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUTF16DYNAMIC.
    virtual void echoUTF16DYNAMIC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUTF16DYNAMIC_ReqArg1, std::string _echoUTF16DYNAMIC_ReqArg2, echoUTF16DYNAMICReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the UTF16 string of fixed length passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUTF16FIXED.
    virtual void echoUTF16FIXED(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _echoUTF16FIXED_ReqArg1, echoUTF16FIXEDReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the UTF8 string of dynamic length passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUTF8DYNAMIC.
    virtual void echoUTF8DYNAMIC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _echoUTF8DYNAMIC_ReqArg1, std::string _echoUTF8DYNAMIC_ReqArg2, echoUTF8DYNAMICReply_t _reply) = 0;
    /*
     * description: 
     * Returns back the UTF8 string of fixed length passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUTF8FIXED.
    virtual void echoUTF8FIXED(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _echoUTF8FIXED_ReqArg1, echoUTF8FIXEDReply_t _reply) = 0;
    /*
     * description: 
     * Reset interface to default values.
     */
    /// This is the method that will be called on remote calls on the method resetInterface.
    virtual void resetInterface(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /*
     * description: 
     * Suspend inteface by stopping offer and resume afterwards.
     */
    /// This is the method that will be called on remote calls on the method suspendInterface.
    virtual void suspendInterface(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _suspendInterface_ReqArg1, uint32_t _suspendInterface_ReqArg2) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of type uint8.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8.
    virtual void triggerEventUINT8(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8_ReqArg1, uint32_t _triggerEventUINT8_ReqArg2, uint32_t _triggerEventUINT8_ReqArg3) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of type array of uint8.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8Array.
    virtual void triggerEventUINT8Array(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8Array_ReqArg1, uint32_t _triggerEventUINT8Array_ReqArg2, uint32_t _triggerEventUINT8Array_ReqArg3) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of e2e data.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8E2E.
    virtual void triggerEventUINT8E2E(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8E2E_ReqArg1, uint32_t _triggerEventUINT8E2E_ReqArg2, uint32_t _triggerEventUINT8E2E_ReqArg3) = 0;
    /*
     * description: 
     * Requests to trigger an broadcast event of multicast type.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8Multicast.
    virtual void triggerEventUINT8Multicast(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT8Multicast_ReqArg1, uint32_t _triggerEventUINT8Multicast_ReqArg2, uint32_t _triggerEventUINT8Multicast_ReqArg3) = 0;
    /*
     * description: 
     * A broadcast event of type uint8 triggered on triggerEventUINT8 method request.
     */
    /// Sends a broadcast event for TestEventUINT8.
    virtual void fireTestEventUINT8Event(const uint8_t &_uINT8Value) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT8Event(_uINT8Value);
    }
    /*
     * description: 
     * A broadcast event of type array of uint8 triggered on triggerEventUINT8Array method request.
     */
    /// Sends a broadcast event for TestEventUINT8Array.
    virtual void fireTestEventUINT8ArrayEvent(const std::vector< uint8_t > &_uINT8Array) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT8ArrayEvent(_uINT8Array);
    }
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8E2E method request.
     */
    /// Sends a broadcast event for TestEventUINT8E2E.
    virtual void fireTestEventUINT8E2EEvent(const uint16_t &_length, const uint16_t &_counter, const uint32_t &_dataID, const uint32_t &_CRC, const uint8_t &_uINT8Value) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT8E2EEvent(_length, _counter, _dataID, _CRC, _uINT8Value);
    }
    /*
     * description: 
     * Returns back the e2e data passed as input parameter.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8E2E.
    virtual void echoUINT8E2E(const std::shared_ptr<CommonAPI::ClientId> _client, uint16_t _echoUINT8E2E_ReqArg1, uint16_t _echoUINT8E2E_ReqArg2, uint32_t _echoUINT8E2E_ReqArg3, uint32_t _echoUINT8E2E_ReqArg4, uint8_t _echoUINT8E2E_ReqArg5, echoUINT8E2EReply_t _reply) = 0;
    /*
     * description: 
     * A broadcast e2e event triggered on triggerEventUINT8Multicast method request.
     */
    /// Sends a broadcast event for TestEventUINT8Multicast.
    virtual void fireTestEventUINT8MulticastEvent(const uint8_t &_uINT8Value) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT8MulticastEvent(_uINT8Value);
    }
    /*
     * description: 
     * Sends the uint8 array over SOME/IP TP.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8ArrayLengthTP.
    virtual void echoUINT8ArrayLengthTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _inUINT8Array_ReqArg1, echoUINT8ArrayLengthTPReply_t _reply) = 0;
    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8ArrayLengthInTP.
    virtual void echoUINT8ArrayLengthInTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _inUINT8Array_ReqArg1, echoUINT8ArrayLengthInTPReply_t _reply) = 0;
    /*
     * description: 
     * Sends the uint8 array as reply over SOME/IP TP.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8ArrayLengthOutTP.
    virtual void echoUINT8ArrayLengthOutTP(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _inUINT32_ReqArg1, echoUINT8ArrayLengthOutTPReply_t _reply) = 0;
    /*
     * description: 
     * Sends the uint8 array as input over SOME/IP TP.
     */
    /// This is the method that will be called on remote calls on the method echoUINT8ArrayLengthTPNoResponse.
    virtual void echoUINT8ArrayLengthTPNoResponse(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _echoUINT8ArrayLengthTPNoResponse_ReqArg1) = 0;
    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8ArrayTP.
    virtual void triggerEventUINT8ArrayTP(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector< uint8_t > _triggerEventUINT8ArrayTP_ReqArg1) = 0;
    /*
     * description: 
     * A broadcast TP event triggered on triggerEventUINT8ArrayTP method request.
     */
    /// Sends a broadcast event for TestEventUINT8ArrayTP.
    virtual void fireTestEventUINT8ArrayTPEvent(const std::vector< uint8_t > &_outUINT8EventArray) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT8ArrayTPEvent(_outUINT8EventArray);
    }
    /*
     * description: 
     * Requests to triggers an TP Event of type uint8 array.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT8ArrayTPNoReqTPPayload.
    virtual void triggerEventUINT8ArrayTPNoReqTPPayload(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) = 0;
    /*
     * description: 
     * Requests to triggers an periodic event of type uint32.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT32Periodic.
    virtual void triggerEventUINT32Periodic(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) = 0;
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32Periodic method request.
     */
    /// Sends a broadcast event for TestEventUINT32Periodic.
    virtual void fireTestEventUINT32PeriodicEvent(const uint32_t &_uINT32Value) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT32PeriodicEvent(_uINT32Value);
    }
    /*
     * description: 
     * Requests to triggers an on change event of type uint32.
     */
    /// This is the method that will be called on remote calls on the method triggerEventUINT32UpdateOnChange.
    virtual void triggerEventUINT32UpdateOnChange(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _triggerEventUINT32_ReqArg1) = 0;
    /*
     * description: 
     * A broadcast periodic event triggered on triggerEventUINT32UpdateOnChange method request.
     */
    /// Sends a broadcast event for TestEventUINT32UpdateOnChange.
    virtual void fireTestEventUINT32UpdateOnChangeEvent(const uint32_t &_uINT32Value) {
        auto stubAdapter = CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireTestEventUINT32UpdateOnChangeEvent(_uINT32Value);
    }
    /*
     * description: 
     * Activates Test Service in the server side.
     */
    /// This is the method that will be called on remote calls on the method activateTestSerivce.
    virtual void activateTestSerivce(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2) = 0;
    /*
     * description: 
     * Deactivates Test Service in the server side.
     */
    /// This is the method that will be called on remote calls on the method deactivateTestSerivce.
    virtual void deactivateTestSerivce(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _activateTestSerivce_ReqArg1, uint32_t _activateTestSerivce_ReqArg2) = 0;


    using CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<ETSStubAdapter, ETSStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef ETSStubRemoteEvent RemoteEventType;
    typedef ETS StubInterface;
};

} // namespace testability
} // namespace someip
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_STUB_HPP_
