/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * First Test Service for service port validation.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_Test_Service1_PROXY_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_Test_Service1_PROXY_HPP_

#include <v1/someip/testability/ETSTestService1ProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace someip {
namespace testability {

template <typename ... _AttributeExtensions>
class ETSTestService1Proxy
    : virtual public ETSTestService1,
      virtual public ETSTestService1ProxyBase,
      virtual public _AttributeExtensions... {
public:
    ETSTestService1Proxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ETSTestService1Proxy();

    typedef ETSTestService1 InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * Sends the uint32 value as reply.
     * Calls echoUINT32 with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void echoUINT32(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls echoUINT32 with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> echoUINT32Async(const uint32_t &_inUINT32_ReqArg1, EchoUINT32AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< ETSTestService1ProxyBase> delegate_;
};

typedef ETSTestService1Proxy<> ETSTestService1ProxyDefault;


//
// ETSTestService1Proxy Implementation
//
template <typename ... _AttributeExtensions>
ETSTestService1Proxy<_AttributeExtensions...>::ETSTestService1Proxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ETSTestService1ProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ETSTestService1ProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ETSTestService1Proxy<_AttributeExtensions...>::~ETSTestService1Proxy() {
}

/*
 * description: 
 * Sends the uint32 value as reply.
 */
template <typename ... _AttributeExtensions>
void ETSTestService1Proxy<_AttributeExtensions...>::echoUINT32(uint32_t _inUINT32_ReqArg1, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_outUINT32_ResArg1, const CommonAPI::CallInfo *_info) {
    delegate_->echoUINT32(_inUINT32_ReqArg1, _internalCallStatus, _outUINT32_ResArg1, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ETSTestService1Proxy<_AttributeExtensions...>::echoUINT32Async(const uint32_t &_inUINT32_ReqArg1, EchoUINT32AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->echoUINT32Async(_inUINT32_ReqArg1, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ETSTestService1Proxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ETSTestService1Proxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ETSTestService1Proxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ETSTestService1Proxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ETSTestService1Proxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ETSTestService1Proxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace testability
} // namespace someip
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_Test_Service1_PROXY_HPP_
