/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * First Test Service for service port validation.
 */
#ifndef V1_SOMEIP_TESTABILITY_ETS_Test_Service1_STUB_DEFAULT_HPP_
#define V1_SOMEIP_TESTABILITY_ETS_Test_Service1_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/someip/testability/ETSTestService1Stub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace someip {
namespace testability {

/**
 * Provides a default implementation for ETSTestService1StubRemoteEvent and
 * ETSTestService1Stub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT ETSTestService1StubDefault
    : public virtual ETSTestService1Stub {
public:
    COMMONAPI_EXPORT ETSTestService1StubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(ETSTestService1::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT ETSTestService1StubRemoteEvent* initStubAdapter(const std::shared_ptr< ETSTestService1StubAdapter> &_adapter) {
        CommonAPI::Stub<ETSTestService1StubAdapter, ETSTestService1StubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * Sends the uint32 value as reply.
     */
    COMMONAPI_EXPORT virtual void echoUINT32(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _inUINT32_ReqArg1, echoUINT32Reply_t _reply) {
        (void)_client;
        (void)_inUINT32_ReqArg1;
        uint32_t outUINT32_ResArg1 = 0ul;
        _reply(outUINT32_ResArg1);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual ETSTestService1StubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(ETSTestService1StubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        ETSTestService1StubDefault *defaultStub_;
    };
protected:
    ETSTestService1StubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace testability
} // namespace someip
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_SOMEIP_TESTABILITY_ETS_Test_Service1_STUB_DEFAULT
