/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_DEMO_Demo_App1_PROXY_BASE_HPP_
#define V0_COMMONAPI_DEMO_Demo_App1_PROXY_BASE_HPP_

#include <v0/commonapi/demo/DemoApp1.hpp>


#include <v0/commonapi/demo/CommonTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace demo {

class DemoApp1ProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        int32_t
    > DemoStatus1Event;
    typedef CommonAPI::Event<
    > DemoStatus2Event;
    typedef CommonAPI::ObservableAttribute<int32_t> UiDemoAttr1Attribute;
    typedef CommonAPI::ObservableAttribute<::v0::commonapi::demo::CommonTypes::a1Struct> A1DemoAttribute;

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> DemoMethod1AsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const DemoApp1::stdErrorTypeEnum&, const std::string&)> DemoMethodErr1AsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> DemoMethodTp1AsyncCallback;

    virtual void DemoMethod1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DemoMethod1Async(const std::string &_name, DemoMethod1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void DemoMethodErr1(std::string _name, CommonAPI::CallStatus &_internalCallStatus, DemoApp1::stdErrorTypeEnum &_error, std::string &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DemoMethodErr1Async(const std::string &_name, DemoMethodErr1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void DemoMethodTp1(std::string _name, std::vector< int32_t > _data, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DemoMethodTp1Async(const std::string &_name, const std::vector< int32_t > &_data, DemoMethodTp1AsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual DemoStatus1Event& getDemoStatus1Event() = 0;
    virtual DemoStatus2Event& getDemoStatus2Event() = 0;
    virtual UiDemoAttr1Attribute& getUiDemoAttr1Attribute() = 0;
    virtual A1DemoAttribute& getA1DemoAttribute() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace demo
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_DEMO_Demo_App1_PROXY_BASE_HPP_
